/*
Mistral AI API

Testing DeprecatedFineTuningAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cterence/mistral-client-golang"
)

func Test_mistral_DeprecatedFineTuningAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DeprecatedFineTuningAPIService JobsApiRoutesFineTuningCancelFineTuningJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jobId string

		resp, httpRes, err := apiClient.DeprecatedFineTuningAPI.JobsApiRoutesFineTuningCancelFineTuningJob(context.Background(), jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeprecatedFineTuningAPIService JobsApiRoutesFineTuningCreateFineTuningJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DeprecatedFineTuningAPI.JobsApiRoutesFineTuningCreateFineTuningJob(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeprecatedFineTuningAPIService JobsApiRoutesFineTuningGetFineTuningJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jobId string

		resp, httpRes, err := apiClient.DeprecatedFineTuningAPI.JobsApiRoutesFineTuningGetFineTuningJob(context.Background(), jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeprecatedFineTuningAPIService JobsApiRoutesFineTuningGetFineTuningJobs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DeprecatedFineTuningAPI.JobsApiRoutesFineTuningGetFineTuningJobs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeprecatedFineTuningAPIService JobsApiRoutesFineTuningStartFineTuningJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jobId string

		resp, httpRes, err := apiClient.DeprecatedFineTuningAPI.JobsApiRoutesFineTuningStartFineTuningJob(context.Background(), jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
