/*
Mistral AI API

Testing BetaWorkflowsExecutionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cterence/mistral-client-golang"
)

func Test_mistral_BetaWorkflowsExecutionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BetaWorkflowsExecutionsAPIService BatchCancelWorkflowExecutionsV1WorkflowsExecutionsCancelPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.BatchCancelWorkflowExecutionsV1WorkflowsExecutionsCancelPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService BatchTerminateWorkflowExecutionsV1WorkflowsExecutionsTerminatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.BatchTerminateWorkflowExecutionsV1WorkflowsExecutionsTerminatePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService CancelWorkflowExecutionV1WorkflowsExecutionsExecutionIdCancelPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.CancelWorkflowExecutionV1WorkflowsExecutionsExecutionIdCancelPost(context.Background(), executionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService GetWorkflowExecutionHistoryV1WorkflowsExecutionsExecutionIdHistoryGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.GetWorkflowExecutionHistoryV1WorkflowsExecutionsExecutionIdHistoryGet(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService GetWorkflowExecutionTraceEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.GetWorkflowExecutionTraceEvents(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService GetWorkflowExecutionTraceOtel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.GetWorkflowExecutionTraceOtel(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService GetWorkflowExecutionTraceSummary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.GetWorkflowExecutionTraceSummary(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService GetWorkflowExecutionV1WorkflowsExecutionsExecutionIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.GetWorkflowExecutionV1WorkflowsExecutionsExecutionIdGet(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService QueryWorkflowExecutionV1WorkflowsExecutionsExecutionIdQueriesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.QueryWorkflowExecutionV1WorkflowsExecutionsExecutionIdQueriesPost(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService ResetWorkflowV1WorkflowsExecutionsExecutionIdResetPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.ResetWorkflowV1WorkflowsExecutionsExecutionIdResetPost(context.Background(), executionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPost(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService StreamV1WorkflowsExecutionsExecutionIdStreamGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.StreamV1WorkflowsExecutionsExecutionIdStreamGet(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService TerminateWorkflowExecutionV1WorkflowsExecutionsExecutionIdTerminatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.TerminateWorkflowExecutionV1WorkflowsExecutionsExecutionIdTerminatePost(context.Background(), executionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsExecutionsAPIService UpdateWorkflowExecutionV1WorkflowsExecutionsExecutionIdUpdatesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var executionId string

		resp, httpRes, err := apiClient.BetaWorkflowsExecutionsAPI.UpdateWorkflowExecutionV1WorkflowsExecutionsExecutionIdUpdatesPost(context.Background(), executionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
