/*
Mistral AI API

Testing AudioVoicesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cterence/mistral-client-golang"
)

func Test_mistral_AudioVoicesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AudioVoicesAPIService CreateVoiceV1AudioVoicesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AudioVoicesAPI.CreateVoiceV1AudioVoicesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AudioVoicesAPIService DeleteVoiceV1AudioVoicesVoiceIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var voiceId string

		resp, httpRes, err := apiClient.AudioVoicesAPI.DeleteVoiceV1AudioVoicesVoiceIdDelete(context.Background(), voiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AudioVoicesAPIService GetVoiceSampleAudioV1AudioVoicesVoiceIdSampleGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var voiceId string

		resp, httpRes, err := apiClient.AudioVoicesAPI.GetVoiceSampleAudioV1AudioVoicesVoiceIdSampleGet(context.Background(), voiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AudioVoicesAPIService GetVoiceV1AudioVoicesVoiceIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var voiceId string

		resp, httpRes, err := apiClient.AudioVoicesAPI.GetVoiceV1AudioVoicesVoiceIdGet(context.Background(), voiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AudioVoicesAPIService ListVoicesV1AudioVoicesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AudioVoicesAPI.ListVoicesV1AudioVoicesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AudioVoicesAPIService UpdateVoiceV1AudioVoicesVoiceIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var voiceId string

		resp, httpRes, err := apiClient.AudioVoicesAPI.UpdateVoiceV1AudioVoicesVoiceIdPatch(context.Background(), voiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
