/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CampaignSelectedEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignSelectedEvents{}

// CampaignSelectedEvents struct for CampaignSelectedEvents
type CampaignSelectedEvents struct {
	CompletionEvents PaginatedResultChatCompletionEventPreview `json:"completion_events"`
}

type _CampaignSelectedEvents CampaignSelectedEvents

// NewCampaignSelectedEvents instantiates a new CampaignSelectedEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignSelectedEvents(completionEvents PaginatedResultChatCompletionEventPreview) *CampaignSelectedEvents {
	this := CampaignSelectedEvents{}
	this.CompletionEvents = completionEvents
	return &this
}

// NewCampaignSelectedEventsWithDefaults instantiates a new CampaignSelectedEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignSelectedEventsWithDefaults() *CampaignSelectedEvents {
	this := CampaignSelectedEvents{}
	return &this
}

// GetCompletionEvents returns the CompletionEvents field value
func (o *CampaignSelectedEvents) GetCompletionEvents() PaginatedResultChatCompletionEventPreview {
	if o == nil {
		var ret PaginatedResultChatCompletionEventPreview
		return ret
	}

	return o.CompletionEvents
}

// GetCompletionEventsOk returns a tuple with the CompletionEvents field value
// and a boolean to check if the value has been set.
func (o *CampaignSelectedEvents) GetCompletionEventsOk() (*PaginatedResultChatCompletionEventPreview, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompletionEvents, true
}

// SetCompletionEvents sets field value
func (o *CampaignSelectedEvents) SetCompletionEvents(v PaginatedResultChatCompletionEventPreview) {
	o.CompletionEvents = v
}

func (o CampaignSelectedEvents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignSelectedEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["completion_events"] = o.CompletionEvents
	return toSerialize, nil
}

func (o *CampaignSelectedEvents) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"completion_events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaignSelectedEvents := _CampaignSelectedEvents{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCampaignSelectedEvents)

	if err != nil {
		return err
	}

	*o = CampaignSelectedEvents(varCampaignSelectedEvents)

	return err
}

type NullableCampaignSelectedEvents struct {
	value *CampaignSelectedEvents
	isSet bool
}

func (v NullableCampaignSelectedEvents) Get() *CampaignSelectedEvents {
	return v.value
}

func (v *NullableCampaignSelectedEvents) Set(val *CampaignSelectedEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignSelectedEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignSelectedEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignSelectedEvents(val *CampaignSelectedEvents) *NullableCampaignSelectedEvents {
	return &NullableCampaignSelectedEvents{value: val, isSet: true}
}

func (v NullableCampaignSelectedEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignSelectedEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


