/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowWithWorkerStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowWithWorkerStatus{}

// WorkflowWithWorkerStatus struct for WorkflowWithWorkerStatus
type WorkflowWithWorkerStatus struct {
	// Unique identifier of the workflow
	Id string `json:"id"`
	// Name of the workflow
	Name string `json:"name"`
	// Display name of the workflow
	DisplayName string `json:"display_name"`
	// Type of the workflow
	Type WorkflowType `json:"type"`
	// Description of the workflow
	Description NullableString `json:"description,omitempty"`
	// Customer ID of the workflow
	CustomerId string `json:"customer_id"`
	// Workspace ID of the workflow
	WorkspaceId string `json:"workspace_id"`
	// Reserved namespace for shared workflows (e.g., 'shared:my-shared-workflow')
	SharedNamespace NullableString `json:"shared_namespace,omitempty"`
	// Whether the workflow is available in chat assistant
	AvailableInChatAssistant *bool `json:"available_in_chat_assistant,omitempty"`
	// Whether the workflow is technical (e.g. SDK-managed)
	IsTechnical *bool `json:"is_technical,omitempty"`
	// Whether the workflow is archived
	Archived *bool `json:"archived,omitempty"`
	// Whether the workflow is active
	Active bool `json:"active"`
}

type _WorkflowWithWorkerStatus WorkflowWithWorkerStatus

// NewWorkflowWithWorkerStatus instantiates a new WorkflowWithWorkerStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowWithWorkerStatus(id string, name string, displayName string, type_ WorkflowType, customerId string, workspaceId string, active bool) *WorkflowWithWorkerStatus {
	this := WorkflowWithWorkerStatus{}
	this.Id = id
	this.Name = name
	this.DisplayName = displayName
	this.Type = type_
	this.CustomerId = customerId
	this.WorkspaceId = workspaceId
	var availableInChatAssistant bool = false
	this.AvailableInChatAssistant = &availableInChatAssistant
	var isTechnical bool = false
	this.IsTechnical = &isTechnical
	var archived bool = false
	this.Archived = &archived
	this.Active = active
	return &this
}

// NewWorkflowWithWorkerStatusWithDefaults instantiates a new WorkflowWithWorkerStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowWithWorkerStatusWithDefaults() *WorkflowWithWorkerStatus {
	this := WorkflowWithWorkerStatus{}
	var availableInChatAssistant bool = false
	this.AvailableInChatAssistant = &availableInChatAssistant
	var isTechnical bool = false
	this.IsTechnical = &isTechnical
	var archived bool = false
	this.Archived = &archived
	return &this
}

// GetId returns the Id field value
func (o *WorkflowWithWorkerStatus) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkflowWithWorkerStatus) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *WorkflowWithWorkerStatus) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkflowWithWorkerStatus) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *WorkflowWithWorkerStatus) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *WorkflowWithWorkerStatus) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetType returns the Type field value
func (o *WorkflowWithWorkerStatus) GetType() WorkflowType {
	if o == nil {
		var ret WorkflowType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetTypeOk() (*WorkflowType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WorkflowWithWorkerStatus) SetType(v WorkflowType) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowWithWorkerStatus) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowWithWorkerStatus) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *WorkflowWithWorkerStatus) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *WorkflowWithWorkerStatus) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *WorkflowWithWorkerStatus) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *WorkflowWithWorkerStatus) UnsetDescription() {
	o.Description.Unset()
}

// GetCustomerId returns the CustomerId field value
func (o *WorkflowWithWorkerStatus) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *WorkflowWithWorkerStatus) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *WorkflowWithWorkerStatus) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *WorkflowWithWorkerStatus) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetSharedNamespace returns the SharedNamespace field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowWithWorkerStatus) GetSharedNamespace() string {
	if o == nil || IsNil(o.SharedNamespace.Get()) {
		var ret string
		return ret
	}
	return *o.SharedNamespace.Get()
}

// GetSharedNamespaceOk returns a tuple with the SharedNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowWithWorkerStatus) GetSharedNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SharedNamespace.Get(), o.SharedNamespace.IsSet()
}

// HasSharedNamespace returns a boolean if a field has been set.
func (o *WorkflowWithWorkerStatus) HasSharedNamespace() bool {
	if o != nil && o.SharedNamespace.IsSet() {
		return true
	}

	return false
}

// SetSharedNamespace gets a reference to the given NullableString and assigns it to the SharedNamespace field.
func (o *WorkflowWithWorkerStatus) SetSharedNamespace(v string) {
	o.SharedNamespace.Set(&v)
}
// SetSharedNamespaceNil sets the value for SharedNamespace to be an explicit nil
func (o *WorkflowWithWorkerStatus) SetSharedNamespaceNil() {
	o.SharedNamespace.Set(nil)
}

// UnsetSharedNamespace ensures that no value is present for SharedNamespace, not even an explicit nil
func (o *WorkflowWithWorkerStatus) UnsetSharedNamespace() {
	o.SharedNamespace.Unset()
}

// GetAvailableInChatAssistant returns the AvailableInChatAssistant field value if set, zero value otherwise.
func (o *WorkflowWithWorkerStatus) GetAvailableInChatAssistant() bool {
	if o == nil || IsNil(o.AvailableInChatAssistant) {
		var ret bool
		return ret
	}
	return *o.AvailableInChatAssistant
}

// GetAvailableInChatAssistantOk returns a tuple with the AvailableInChatAssistant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetAvailableInChatAssistantOk() (*bool, bool) {
	if o == nil || IsNil(o.AvailableInChatAssistant) {
		return nil, false
	}
	return o.AvailableInChatAssistant, true
}

// HasAvailableInChatAssistant returns a boolean if a field has been set.
func (o *WorkflowWithWorkerStatus) HasAvailableInChatAssistant() bool {
	if o != nil && !IsNil(o.AvailableInChatAssistant) {
		return true
	}

	return false
}

// SetAvailableInChatAssistant gets a reference to the given bool and assigns it to the AvailableInChatAssistant field.
func (o *WorkflowWithWorkerStatus) SetAvailableInChatAssistant(v bool) {
	o.AvailableInChatAssistant = &v
}

// GetIsTechnical returns the IsTechnical field value if set, zero value otherwise.
func (o *WorkflowWithWorkerStatus) GetIsTechnical() bool {
	if o == nil || IsNil(o.IsTechnical) {
		var ret bool
		return ret
	}
	return *o.IsTechnical
}

// GetIsTechnicalOk returns a tuple with the IsTechnical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetIsTechnicalOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTechnical) {
		return nil, false
	}
	return o.IsTechnical, true
}

// HasIsTechnical returns a boolean if a field has been set.
func (o *WorkflowWithWorkerStatus) HasIsTechnical() bool {
	if o != nil && !IsNil(o.IsTechnical) {
		return true
	}

	return false
}

// SetIsTechnical gets a reference to the given bool and assigns it to the IsTechnical field.
func (o *WorkflowWithWorkerStatus) SetIsTechnical(v bool) {
	o.IsTechnical = &v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *WorkflowWithWorkerStatus) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *WorkflowWithWorkerStatus) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *WorkflowWithWorkerStatus) SetArchived(v bool) {
	o.Archived = &v
}

// GetActive returns the Active field value
func (o *WorkflowWithWorkerStatus) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *WorkflowWithWorkerStatus) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *WorkflowWithWorkerStatus) SetActive(v bool) {
	o.Active = v
}

func (o WorkflowWithWorkerStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowWithWorkerStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["display_name"] = o.DisplayName
	toSerialize["type"] = o.Type
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["workspace_id"] = o.WorkspaceId
	if o.SharedNamespace.IsSet() {
		toSerialize["shared_namespace"] = o.SharedNamespace.Get()
	}
	if !IsNil(o.AvailableInChatAssistant) {
		toSerialize["available_in_chat_assistant"] = o.AvailableInChatAssistant
	}
	if !IsNil(o.IsTechnical) {
		toSerialize["is_technical"] = o.IsTechnical
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	toSerialize["active"] = o.Active
	return toSerialize, nil
}

func (o *WorkflowWithWorkerStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"display_name",
		"type",
		"customer_id",
		"workspace_id",
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowWithWorkerStatus := _WorkflowWithWorkerStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowWithWorkerStatus)

	if err != nil {
		return err
	}

	*o = WorkflowWithWorkerStatus(varWorkflowWithWorkerStatus)

	return err
}

type NullableWorkflowWithWorkerStatus struct {
	value *WorkflowWithWorkerStatus
	isSet bool
}

func (v NullableWorkflowWithWorkerStatus) Get() *WorkflowWithWorkerStatus {
	return v.value
}

func (v *NullableWorkflowWithWorkerStatus) Set(val *WorkflowWithWorkerStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowWithWorkerStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowWithWorkerStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowWithWorkerStatus(val *WorkflowWithWorkerStatus) *NullableWorkflowWithWorkerStatus {
	return &NullableWorkflowWithWorkerStatus{value: val, isSet: true}
}

func (v NullableWorkflowWithWorkerStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowWithWorkerStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


