/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JudgeClassificationOutputOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JudgeClassificationOutputOption{}

// JudgeClassificationOutputOption struct for JudgeClassificationOutputOption
type JudgeClassificationOutputOption struct {
	Value string `json:"value"`
	Description string `json:"description"`
}

type _JudgeClassificationOutputOption JudgeClassificationOutputOption

// NewJudgeClassificationOutputOption instantiates a new JudgeClassificationOutputOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJudgeClassificationOutputOption(value string, description string) *JudgeClassificationOutputOption {
	this := JudgeClassificationOutputOption{}
	this.Value = value
	this.Description = description
	return &this
}

// NewJudgeClassificationOutputOptionWithDefaults instantiates a new JudgeClassificationOutputOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJudgeClassificationOutputOptionWithDefaults() *JudgeClassificationOutputOption {
	this := JudgeClassificationOutputOption{}
	return &this
}

// GetValue returns the Value field value
func (o *JudgeClassificationOutputOption) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *JudgeClassificationOutputOption) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *JudgeClassificationOutputOption) SetValue(v string) {
	o.Value = v
}

// GetDescription returns the Description field value
func (o *JudgeClassificationOutputOption) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *JudgeClassificationOutputOption) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *JudgeClassificationOutputOption) SetDescription(v string) {
	o.Description = v
}

func (o JudgeClassificationOutputOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JudgeClassificationOutputOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *JudgeClassificationOutputOption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJudgeClassificationOutputOption := _JudgeClassificationOutputOption{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJudgeClassificationOutputOption)

	if err != nil {
		return err
	}

	*o = JudgeClassificationOutputOption(varJudgeClassificationOutputOption)

	return err
}

type NullableJudgeClassificationOutputOption struct {
	value *JudgeClassificationOutputOption
	isSet bool
}

func (v NullableJudgeClassificationOutputOption) Get() *JudgeClassificationOutputOption {
	return v.value
}

func (v *NullableJudgeClassificationOutputOption) Set(val *JudgeClassificationOutputOption) {
	v.value = val
	v.isSet = true
}

func (v NullableJudgeClassificationOutputOption) IsSet() bool {
	return v.isSet
}

func (v *NullableJudgeClassificationOutputOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJudgeClassificationOutputOption(val *JudgeClassificationOutputOption) *NullableJudgeClassificationOutputOption {
	return &NullableJudgeClassificationOutputOption{value: val, isSet: true}
}

func (v NullableJudgeClassificationOutputOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJudgeClassificationOutputOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


