/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowTaskFailedAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowTaskFailedAttributes{}

// WorkflowTaskFailedAttributes Attributes for workflow task failed events.
type WorkflowTaskFailedAttributes struct {
	// Unique identifier for the task within the workflow execution.
	TaskId string `json:"task_id"`
	// Details about the failure that caused the task to fail.
	Failure Failure `json:"failure"`
}

type _WorkflowTaskFailedAttributes WorkflowTaskFailedAttributes

// NewWorkflowTaskFailedAttributes instantiates a new WorkflowTaskFailedAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowTaskFailedAttributes(taskId string, failure Failure) *WorkflowTaskFailedAttributes {
	this := WorkflowTaskFailedAttributes{}
	this.TaskId = taskId
	this.Failure = failure
	return &this
}

// NewWorkflowTaskFailedAttributesWithDefaults instantiates a new WorkflowTaskFailedAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowTaskFailedAttributesWithDefaults() *WorkflowTaskFailedAttributes {
	this := WorkflowTaskFailedAttributes{}
	return &this
}

// GetTaskId returns the TaskId field value
func (o *WorkflowTaskFailedAttributes) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *WorkflowTaskFailedAttributes) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *WorkflowTaskFailedAttributes) SetTaskId(v string) {
	o.TaskId = v
}

// GetFailure returns the Failure field value
func (o *WorkflowTaskFailedAttributes) GetFailure() Failure {
	if o == nil {
		var ret Failure
		return ret
	}

	return o.Failure
}

// GetFailureOk returns a tuple with the Failure field value
// and a boolean to check if the value has been set.
func (o *WorkflowTaskFailedAttributes) GetFailureOk() (*Failure, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failure, true
}

// SetFailure sets field value
func (o *WorkflowTaskFailedAttributes) SetFailure(v Failure) {
	o.Failure = v
}

func (o WorkflowTaskFailedAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowTaskFailedAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["task_id"] = o.TaskId
	toSerialize["failure"] = o.Failure
	return toSerialize, nil
}

func (o *WorkflowTaskFailedAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"task_id",
		"failure",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowTaskFailedAttributes := _WorkflowTaskFailedAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowTaskFailedAttributes)

	if err != nil {
		return err
	}

	*o = WorkflowTaskFailedAttributes(varWorkflowTaskFailedAttributes)

	return err
}

type NullableWorkflowTaskFailedAttributes struct {
	value *WorkflowTaskFailedAttributes
	isSet bool
}

func (v NullableWorkflowTaskFailedAttributes) Get() *WorkflowTaskFailedAttributes {
	return v.value
}

func (v *NullableWorkflowTaskFailedAttributes) Set(val *WorkflowTaskFailedAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowTaskFailedAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowTaskFailedAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowTaskFailedAttributes(val *WorkflowTaskFailedAttributes) *NullableWorkflowTaskFailedAttributes {
	return &NullableWorkflowTaskFailedAttributes{value: val, isSet: true}
}

func (v NullableWorkflowTaskFailedAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowTaskFailedAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


