/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RealtimeTranscriptionInputAudioAppend type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RealtimeTranscriptionInputAudioAppend{}

// RealtimeTranscriptionInputAudioAppend struct for RealtimeTranscriptionInputAudioAppend
type RealtimeTranscriptionInputAudioAppend struct {
	Type *string `json:"type,omitempty"`
	// Base64-encoded raw PCM bytes matching the current audio_format. Max decoded size: 262144 bytes.
	Audio string `json:"audio"`
}

type _RealtimeTranscriptionInputAudioAppend RealtimeTranscriptionInputAudioAppend

// NewRealtimeTranscriptionInputAudioAppend instantiates a new RealtimeTranscriptionInputAudioAppend object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealtimeTranscriptionInputAudioAppend(audio string) *RealtimeTranscriptionInputAudioAppend {
	this := RealtimeTranscriptionInputAudioAppend{}
	var type_ string = "input_audio.append"
	this.Type = &type_
	this.Audio = audio
	return &this
}

// NewRealtimeTranscriptionInputAudioAppendWithDefaults instantiates a new RealtimeTranscriptionInputAudioAppend object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealtimeTranscriptionInputAudioAppendWithDefaults() *RealtimeTranscriptionInputAudioAppend {
	this := RealtimeTranscriptionInputAudioAppend{}
	var type_ string = "input_audio.append"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RealtimeTranscriptionInputAudioAppend) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealtimeTranscriptionInputAudioAppend) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RealtimeTranscriptionInputAudioAppend) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RealtimeTranscriptionInputAudioAppend) SetType(v string) {
	o.Type = &v
}

// GetAudio returns the Audio field value
func (o *RealtimeTranscriptionInputAudioAppend) GetAudio() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Audio
}

// GetAudioOk returns a tuple with the Audio field value
// and a boolean to check if the value has been set.
func (o *RealtimeTranscriptionInputAudioAppend) GetAudioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audio, true
}

// SetAudio sets field value
func (o *RealtimeTranscriptionInputAudioAppend) SetAudio(v string) {
	o.Audio = v
}

func (o RealtimeTranscriptionInputAudioAppend) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RealtimeTranscriptionInputAudioAppend) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["audio"] = o.Audio
	return toSerialize, nil
}

func (o *RealtimeTranscriptionInputAudioAppend) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audio",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRealtimeTranscriptionInputAudioAppend := _RealtimeTranscriptionInputAudioAppend{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRealtimeTranscriptionInputAudioAppend)

	if err != nil {
		return err
	}

	*o = RealtimeTranscriptionInputAudioAppend(varRealtimeTranscriptionInputAudioAppend)

	return err
}

type NullableRealtimeTranscriptionInputAudioAppend struct {
	value *RealtimeTranscriptionInputAudioAppend
	isSet bool
}

func (v NullableRealtimeTranscriptionInputAudioAppend) Get() *RealtimeTranscriptionInputAudioAppend {
	return v.value
}

func (v *NullableRealtimeTranscriptionInputAudioAppend) Set(val *RealtimeTranscriptionInputAudioAppend) {
	v.value = val
	v.isSet = true
}

func (v NullableRealtimeTranscriptionInputAudioAppend) IsSet() bool {
	return v.isSet
}

func (v *NullableRealtimeTranscriptionInputAudioAppend) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealtimeTranscriptionInputAudioAppend(val *RealtimeTranscriptionInputAudioAppend) *NullableRealtimeTranscriptionInputAudioAppend {
	return &NullableRealtimeTranscriptionInputAudioAppend{value: val, isSet: true}
}

func (v NullableRealtimeTranscriptionInputAudioAppend) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealtimeTranscriptionInputAudioAppend) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


