/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DeploymentDetailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentDetailResponse{}

// DeploymentDetailResponse struct for DeploymentDetailResponse
type DeploymentDetailResponse struct {
	// Unique identifier of the deployment
	Id string `json:"id"`
	// Deployment name
	Name string `json:"name"`
	// Whether at least one worker is currently live
	IsActive bool `json:"is_active"`
	// When the deployment was first registered
	CreatedAt time.Time `json:"created_at"`
	// When the deployment was last updated
	UpdatedAt time.Time `json:"updated_at"`
	// Workers registered for the deployment
	Workers []DeploymentWorkerResponse `json:"workers"`
}

type _DeploymentDetailResponse DeploymentDetailResponse

// NewDeploymentDetailResponse instantiates a new DeploymentDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentDetailResponse(id string, name string, isActive bool, createdAt time.Time, updatedAt time.Time, workers []DeploymentWorkerResponse) *DeploymentDetailResponse {
	this := DeploymentDetailResponse{}
	this.Id = id
	this.Name = name
	this.IsActive = isActive
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Workers = workers
	return &this
}

// NewDeploymentDetailResponseWithDefaults instantiates a new DeploymentDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentDetailResponseWithDefaults() *DeploymentDetailResponse {
	this := DeploymentDetailResponse{}
	return &this
}

// GetId returns the Id field value
func (o *DeploymentDetailResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeploymentDetailResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DeploymentDetailResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeploymentDetailResponse) SetName(v string) {
	o.Name = v
}

// GetIsActive returns the IsActive field value
func (o *DeploymentDetailResponse) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailResponse) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *DeploymentDetailResponse) SetIsActive(v bool) {
	o.IsActive = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeploymentDetailResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeploymentDetailResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DeploymentDetailResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DeploymentDetailResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetWorkers returns the Workers field value
func (o *DeploymentDetailResponse) GetWorkers() []DeploymentWorkerResponse {
	if o == nil {
		var ret []DeploymentWorkerResponse
		return ret
	}

	return o.Workers
}

// GetWorkersOk returns a tuple with the Workers field value
// and a boolean to check if the value has been set.
func (o *DeploymentDetailResponse) GetWorkersOk() ([]DeploymentWorkerResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Workers, true
}

// SetWorkers sets field value
func (o *DeploymentDetailResponse) SetWorkers(v []DeploymentWorkerResponse) {
	o.Workers = v
}

func (o DeploymentDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentDetailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["is_active"] = o.IsActive
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["workers"] = o.Workers
	return toSerialize, nil
}

func (o *DeploymentDetailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"is_active",
		"created_at",
		"updated_at",
		"workers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentDetailResponse := _DeploymentDetailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentDetailResponse)

	if err != nil {
		return err
	}

	*o = DeploymentDetailResponse(varDeploymentDetailResponse)

	return err
}

type NullableDeploymentDetailResponse struct {
	value *DeploymentDetailResponse
	isSet bool
}

func (v NullableDeploymentDetailResponse) Get() *DeploymentDetailResponse {
	return v.value
}

func (v *NullableDeploymentDetailResponse) Set(val *DeploymentDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentDetailResponse(val *DeploymentDetailResponse) *NullableDeploymentDetailResponse {
	return &NullableDeploymentDetailResponse{value: val, isSet: true}
}

func (v NullableDeploymentDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


