/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectorMCPCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorMCPCreate{}

// ConnectorMCPCreate struct for ConnectorMCPCreate
type ConnectorMCPCreate struct {
	// The name of the connector. Should be 64 char length maximum, alphanumeric, only underscores/dashes.
	Name string `json:"name"`
	// The description of the connector.
	Description string `json:"description"`
	// The optional url of the icon you want to associate to the connector.
	IconUrl NullableString `json:"icon_url,omitempty"`
	// Visibility of the connector. Use 'shared_workspace' for workspace scoped connectors, or 'private' for private connectors.
	Visibility *ResourceVisibility `json:"visibility,omitempty"`
	// The url of the MCP server.
	Server string `json:"server"`
	// Optional organization-level headers to be sent with the request to the mcp server.
	Headers map[string]interface{} `json:"headers,omitempty"`
	// Optional additional authentication data for the connector.
	AuthData NullableAuthData `json:"auth_data,omitempty"`
	// Optional system prompt for the connector.
	SystemPrompt NullableString `json:"system_prompt,omitempty"`
}

type _ConnectorMCPCreate ConnectorMCPCreate

// NewConnectorMCPCreate instantiates a new ConnectorMCPCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorMCPCreate(name string, description string, server string) *ConnectorMCPCreate {
	this := ConnectorMCPCreate{}
	this.Name = name
	this.Description = description
	var visibility ResourceVisibility = RESOURCEVISIBILITY_SHARED_ORG
	this.Visibility = &visibility
	this.Server = server
	return &this
}

// NewConnectorMCPCreateWithDefaults instantiates a new ConnectorMCPCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorMCPCreateWithDefaults() *ConnectorMCPCreate {
	this := ConnectorMCPCreate{}
	var visibility ResourceVisibility = RESOURCEVISIBILITY_SHARED_ORG
	this.Visibility = &visibility
	return &this
}

// GetName returns the Name field value
func (o *ConnectorMCPCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectorMCPCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectorMCPCreate) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ConnectorMCPCreate) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ConnectorMCPCreate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ConnectorMCPCreate) SetDescription(v string) {
	o.Description = v
}

// GetIconUrl returns the IconUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPCreate) GetIconUrl() string {
	if o == nil || IsNil(o.IconUrl.Get()) {
		var ret string
		return ret
	}
	return *o.IconUrl.Get()
}

// GetIconUrlOk returns a tuple with the IconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPCreate) GetIconUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IconUrl.Get(), o.IconUrl.IsSet()
}

// HasIconUrl returns a boolean if a field has been set.
func (o *ConnectorMCPCreate) HasIconUrl() bool {
	if o != nil && o.IconUrl.IsSet() {
		return true
	}

	return false
}

// SetIconUrl gets a reference to the given NullableString and assigns it to the IconUrl field.
func (o *ConnectorMCPCreate) SetIconUrl(v string) {
	o.IconUrl.Set(&v)
}
// SetIconUrlNil sets the value for IconUrl to be an explicit nil
func (o *ConnectorMCPCreate) SetIconUrlNil() {
	o.IconUrl.Set(nil)
}

// UnsetIconUrl ensures that no value is present for IconUrl, not even an explicit nil
func (o *ConnectorMCPCreate) UnsetIconUrl() {
	o.IconUrl.Unset()
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *ConnectorMCPCreate) GetVisibility() ResourceVisibility {
	if o == nil || IsNil(o.Visibility) {
		var ret ResourceVisibility
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorMCPCreate) GetVisibilityOk() (*ResourceVisibility, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *ConnectorMCPCreate) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given ResourceVisibility and assigns it to the Visibility field.
func (o *ConnectorMCPCreate) SetVisibility(v ResourceVisibility) {
	o.Visibility = &v
}

// GetServer returns the Server field value
func (o *ConnectorMCPCreate) GetServer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Server
}

// GetServerOk returns a tuple with the Server field value
// and a boolean to check if the value has been set.
func (o *ConnectorMCPCreate) GetServerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Server, true
}

// SetServer sets field value
func (o *ConnectorMCPCreate) SetServer(v string) {
	o.Server = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPCreate) GetHeaders() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPCreate) GetHeadersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Headers) {
		return map[string]interface{}{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *ConnectorMCPCreate) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]interface{} and assigns it to the Headers field.
func (o *ConnectorMCPCreate) SetHeaders(v map[string]interface{}) {
	o.Headers = v
}

// GetAuthData returns the AuthData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPCreate) GetAuthData() AuthData {
	if o == nil || IsNil(o.AuthData.Get()) {
		var ret AuthData
		return ret
	}
	return *o.AuthData.Get()
}

// GetAuthDataOk returns a tuple with the AuthData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPCreate) GetAuthDataOk() (*AuthData, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthData.Get(), o.AuthData.IsSet()
}

// HasAuthData returns a boolean if a field has been set.
func (o *ConnectorMCPCreate) HasAuthData() bool {
	if o != nil && o.AuthData.IsSet() {
		return true
	}

	return false
}

// SetAuthData gets a reference to the given NullableAuthData and assigns it to the AuthData field.
func (o *ConnectorMCPCreate) SetAuthData(v AuthData) {
	o.AuthData.Set(&v)
}
// SetAuthDataNil sets the value for AuthData to be an explicit nil
func (o *ConnectorMCPCreate) SetAuthDataNil() {
	o.AuthData.Set(nil)
}

// UnsetAuthData ensures that no value is present for AuthData, not even an explicit nil
func (o *ConnectorMCPCreate) UnsetAuthData() {
	o.AuthData.Unset()
}

// GetSystemPrompt returns the SystemPrompt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPCreate) GetSystemPrompt() string {
	if o == nil || IsNil(o.SystemPrompt.Get()) {
		var ret string
		return ret
	}
	return *o.SystemPrompt.Get()
}

// GetSystemPromptOk returns a tuple with the SystemPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPCreate) GetSystemPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SystemPrompt.Get(), o.SystemPrompt.IsSet()
}

// HasSystemPrompt returns a boolean if a field has been set.
func (o *ConnectorMCPCreate) HasSystemPrompt() bool {
	if o != nil && o.SystemPrompt.IsSet() {
		return true
	}

	return false
}

// SetSystemPrompt gets a reference to the given NullableString and assigns it to the SystemPrompt field.
func (o *ConnectorMCPCreate) SetSystemPrompt(v string) {
	o.SystemPrompt.Set(&v)
}
// SetSystemPromptNil sets the value for SystemPrompt to be an explicit nil
func (o *ConnectorMCPCreate) SetSystemPromptNil() {
	o.SystemPrompt.Set(nil)
}

// UnsetSystemPrompt ensures that no value is present for SystemPrompt, not even an explicit nil
func (o *ConnectorMCPCreate) UnsetSystemPrompt() {
	o.SystemPrompt.Unset()
}

func (o ConnectorMCPCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorMCPCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if o.IconUrl.IsSet() {
		toSerialize["icon_url"] = o.IconUrl.Get()
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	toSerialize["server"] = o.Server
	if o.Headers != nil {
		toSerialize["headers"] = o.Headers
	}
	if o.AuthData.IsSet() {
		toSerialize["auth_data"] = o.AuthData.Get()
	}
	if o.SystemPrompt.IsSet() {
		toSerialize["system_prompt"] = o.SystemPrompt.Get()
	}
	return toSerialize, nil
}

func (o *ConnectorMCPCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"server",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorMCPCreate := _ConnectorMCPCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectorMCPCreate)

	if err != nil {
		return err
	}

	*o = ConnectorMCPCreate(varConnectorMCPCreate)

	return err
}

type NullableConnectorMCPCreate struct {
	value *ConnectorMCPCreate
	isSet bool
}

func (v NullableConnectorMCPCreate) Get() *ConnectorMCPCreate {
	return v.value
}

func (v *NullableConnectorMCPCreate) Set(val *ConnectorMCPCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorMCPCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorMCPCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorMCPCreate(val *ConnectorMCPCreate) *NullableConnectorMCPCreate {
	return &NullableConnectorMCPCreate{value: val, isSet: true}
}

func (v NullableConnectorMCPCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorMCPCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


