/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OCRImageBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OCRImageBlock{}

// OCRImageBlock struct for OCRImageBlock
type OCRImageBlock struct {
	TopLeftX int32 `json:"top_left_x"`
	TopLeftY int32 `json:"top_left_y"`
	BottomRightX int32 `json:"bottom_right_x"`
	BottomRightY int32 `json:"bottom_right_y"`
	// Text/markdown/html content of this block
	Content string `json:"content"`
	Type *string `json:"type,omitempty"`
	// References the corresponding entry in OCRPageObject.images
	ImageId string `json:"image_id"`
}

type _OCRImageBlock OCRImageBlock

// NewOCRImageBlock instantiates a new OCRImageBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOCRImageBlock(topLeftX int32, topLeftY int32, bottomRightX int32, bottomRightY int32, content string, imageId string) *OCRImageBlock {
	this := OCRImageBlock{}
	this.TopLeftX = topLeftX
	this.TopLeftY = topLeftY
	this.BottomRightX = bottomRightX
	this.BottomRightY = bottomRightY
	this.Content = content
	var type_ string = "image"
	this.Type = &type_
	this.ImageId = imageId
	return &this
}

// NewOCRImageBlockWithDefaults instantiates a new OCRImageBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOCRImageBlockWithDefaults() *OCRImageBlock {
	this := OCRImageBlock{}
	var type_ string = "image"
	this.Type = &type_
	return &this
}

// GetTopLeftX returns the TopLeftX field value
func (o *OCRImageBlock) GetTopLeftX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TopLeftX
}

// GetTopLeftXOk returns a tuple with the TopLeftX field value
// and a boolean to check if the value has been set.
func (o *OCRImageBlock) GetTopLeftXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopLeftX, true
}

// SetTopLeftX sets field value
func (o *OCRImageBlock) SetTopLeftX(v int32) {
	o.TopLeftX = v
}

// GetTopLeftY returns the TopLeftY field value
func (o *OCRImageBlock) GetTopLeftY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TopLeftY
}

// GetTopLeftYOk returns a tuple with the TopLeftY field value
// and a boolean to check if the value has been set.
func (o *OCRImageBlock) GetTopLeftYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopLeftY, true
}

// SetTopLeftY sets field value
func (o *OCRImageBlock) SetTopLeftY(v int32) {
	o.TopLeftY = v
}

// GetBottomRightX returns the BottomRightX field value
func (o *OCRImageBlock) GetBottomRightX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BottomRightX
}

// GetBottomRightXOk returns a tuple with the BottomRightX field value
// and a boolean to check if the value has been set.
func (o *OCRImageBlock) GetBottomRightXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BottomRightX, true
}

// SetBottomRightX sets field value
func (o *OCRImageBlock) SetBottomRightX(v int32) {
	o.BottomRightX = v
}

// GetBottomRightY returns the BottomRightY field value
func (o *OCRImageBlock) GetBottomRightY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BottomRightY
}

// GetBottomRightYOk returns a tuple with the BottomRightY field value
// and a boolean to check if the value has been set.
func (o *OCRImageBlock) GetBottomRightYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BottomRightY, true
}

// SetBottomRightY sets field value
func (o *OCRImageBlock) SetBottomRightY(v int32) {
	o.BottomRightY = v
}

// GetContent returns the Content field value
func (o *OCRImageBlock) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *OCRImageBlock) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *OCRImageBlock) SetContent(v string) {
	o.Content = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OCRImageBlock) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OCRImageBlock) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OCRImageBlock) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OCRImageBlock) SetType(v string) {
	o.Type = &v
}

// GetImageId returns the ImageId field value
func (o *OCRImageBlock) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *OCRImageBlock) GetImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *OCRImageBlock) SetImageId(v string) {
	o.ImageId = v
}

func (o OCRImageBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OCRImageBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["top_left_x"] = o.TopLeftX
	toSerialize["top_left_y"] = o.TopLeftY
	toSerialize["bottom_right_x"] = o.BottomRightX
	toSerialize["bottom_right_y"] = o.BottomRightY
	toSerialize["content"] = o.Content
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["image_id"] = o.ImageId
	return toSerialize, nil
}

func (o *OCRImageBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"top_left_x",
		"top_left_y",
		"bottom_right_x",
		"bottom_right_y",
		"content",
		"image_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOCRImageBlock := _OCRImageBlock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOCRImageBlock)

	if err != nil {
		return err
	}

	*o = OCRImageBlock(varOCRImageBlock)

	return err
}

type NullableOCRImageBlock struct {
	value *OCRImageBlock
	isSet bool
}

func (v NullableOCRImageBlock) Get() *OCRImageBlock {
	return v.value
}

func (v *NullableOCRImageBlock) Set(val *OCRImageBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableOCRImageBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableOCRImageBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOCRImageBlock(val *OCRImageBlock) *NullableOCRImageBlock {
	return &NullableOCRImageBlock{value: val, isSet: true}
}

func (v NullableOCRImageBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOCRImageBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


