/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkerInfo{}

// WorkerInfo struct for WorkerInfo
type WorkerInfo struct {
	SchedulerUrl string `json:"scheduler_url"`
	Namespace string `json:"namespace"`
	Tls *bool `json:"tls,omitempty"`
}

type _WorkerInfo WorkerInfo

// NewWorkerInfo instantiates a new WorkerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkerInfo(schedulerUrl string, namespace string) *WorkerInfo {
	this := WorkerInfo{}
	this.SchedulerUrl = schedulerUrl
	this.Namespace = namespace
	var tls bool = false
	this.Tls = &tls
	return &this
}

// NewWorkerInfoWithDefaults instantiates a new WorkerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkerInfoWithDefaults() *WorkerInfo {
	this := WorkerInfo{}
	var tls bool = false
	this.Tls = &tls
	return &this
}

// GetSchedulerUrl returns the SchedulerUrl field value
func (o *WorkerInfo) GetSchedulerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchedulerUrl
}

// GetSchedulerUrlOk returns a tuple with the SchedulerUrl field value
// and a boolean to check if the value has been set.
func (o *WorkerInfo) GetSchedulerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchedulerUrl, true
}

// SetSchedulerUrl sets field value
func (o *WorkerInfo) SetSchedulerUrl(v string) {
	o.SchedulerUrl = v
}

// GetNamespace returns the Namespace field value
func (o *WorkerInfo) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *WorkerInfo) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *WorkerInfo) SetNamespace(v string) {
	o.Namespace = v
}

// GetTls returns the Tls field value if set, zero value otherwise.
func (o *WorkerInfo) GetTls() bool {
	if o == nil || IsNil(o.Tls) {
		var ret bool
		return ret
	}
	return *o.Tls
}

// GetTlsOk returns a tuple with the Tls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkerInfo) GetTlsOk() (*bool, bool) {
	if o == nil || IsNil(o.Tls) {
		return nil, false
	}
	return o.Tls, true
}

// HasTls returns a boolean if a field has been set.
func (o *WorkerInfo) HasTls() bool {
	if o != nil && !IsNil(o.Tls) {
		return true
	}

	return false
}

// SetTls gets a reference to the given bool and assigns it to the Tls field.
func (o *WorkerInfo) SetTls(v bool) {
	o.Tls = &v
}

func (o WorkerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scheduler_url"] = o.SchedulerUrl
	toSerialize["namespace"] = o.Namespace
	if !IsNil(o.Tls) {
		toSerialize["tls"] = o.Tls
	}
	return toSerialize, nil
}

func (o *WorkerInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scheduler_url",
		"namespace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkerInfo := _WorkerInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkerInfo)

	if err != nil {
		return err
	}

	*o = WorkerInfo(varWorkerInfo)

	return err
}

type NullableWorkerInfo struct {
	value *WorkerInfo
	isSet bool
}

func (v NullableWorkerInfo) Get() *WorkerInfo {
	return v.value
}

func (v *NullableWorkerInfo) Set(val *WorkerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkerInfo(val *WorkerInfo) *NullableWorkerInfo {
	return &NullableWorkerInfo{value: val, isSet: true}
}

func (v NullableWorkerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


