/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OCRAsideTextBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OCRAsideTextBlock{}

// OCRAsideTextBlock struct for OCRAsideTextBlock
type OCRAsideTextBlock struct {
	TopLeftX int32 `json:"top_left_x"`
	TopLeftY int32 `json:"top_left_y"`
	BottomRightX int32 `json:"bottom_right_x"`
	BottomRightY int32 `json:"bottom_right_y"`
	// Text/markdown/html content of this block
	Content string `json:"content"`
	Type *string `json:"type,omitempty"`
}

type _OCRAsideTextBlock OCRAsideTextBlock

// NewOCRAsideTextBlock instantiates a new OCRAsideTextBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOCRAsideTextBlock(topLeftX int32, topLeftY int32, bottomRightX int32, bottomRightY int32, content string) *OCRAsideTextBlock {
	this := OCRAsideTextBlock{}
	this.TopLeftX = topLeftX
	this.TopLeftY = topLeftY
	this.BottomRightX = bottomRightX
	this.BottomRightY = bottomRightY
	this.Content = content
	var type_ string = "aside_text"
	this.Type = &type_
	return &this
}

// NewOCRAsideTextBlockWithDefaults instantiates a new OCRAsideTextBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOCRAsideTextBlockWithDefaults() *OCRAsideTextBlock {
	this := OCRAsideTextBlock{}
	var type_ string = "aside_text"
	this.Type = &type_
	return &this
}

// GetTopLeftX returns the TopLeftX field value
func (o *OCRAsideTextBlock) GetTopLeftX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TopLeftX
}

// GetTopLeftXOk returns a tuple with the TopLeftX field value
// and a boolean to check if the value has been set.
func (o *OCRAsideTextBlock) GetTopLeftXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopLeftX, true
}

// SetTopLeftX sets field value
func (o *OCRAsideTextBlock) SetTopLeftX(v int32) {
	o.TopLeftX = v
}

// GetTopLeftY returns the TopLeftY field value
func (o *OCRAsideTextBlock) GetTopLeftY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TopLeftY
}

// GetTopLeftYOk returns a tuple with the TopLeftY field value
// and a boolean to check if the value has been set.
func (o *OCRAsideTextBlock) GetTopLeftYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopLeftY, true
}

// SetTopLeftY sets field value
func (o *OCRAsideTextBlock) SetTopLeftY(v int32) {
	o.TopLeftY = v
}

// GetBottomRightX returns the BottomRightX field value
func (o *OCRAsideTextBlock) GetBottomRightX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BottomRightX
}

// GetBottomRightXOk returns a tuple with the BottomRightX field value
// and a boolean to check if the value has been set.
func (o *OCRAsideTextBlock) GetBottomRightXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BottomRightX, true
}

// SetBottomRightX sets field value
func (o *OCRAsideTextBlock) SetBottomRightX(v int32) {
	o.BottomRightX = v
}

// GetBottomRightY returns the BottomRightY field value
func (o *OCRAsideTextBlock) GetBottomRightY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BottomRightY
}

// GetBottomRightYOk returns a tuple with the BottomRightY field value
// and a boolean to check if the value has been set.
func (o *OCRAsideTextBlock) GetBottomRightYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BottomRightY, true
}

// SetBottomRightY sets field value
func (o *OCRAsideTextBlock) SetBottomRightY(v int32) {
	o.BottomRightY = v
}

// GetContent returns the Content field value
func (o *OCRAsideTextBlock) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *OCRAsideTextBlock) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *OCRAsideTextBlock) SetContent(v string) {
	o.Content = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OCRAsideTextBlock) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OCRAsideTextBlock) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OCRAsideTextBlock) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OCRAsideTextBlock) SetType(v string) {
	o.Type = &v
}

func (o OCRAsideTextBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OCRAsideTextBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["top_left_x"] = o.TopLeftX
	toSerialize["top_left_y"] = o.TopLeftY
	toSerialize["bottom_right_x"] = o.BottomRightX
	toSerialize["bottom_right_y"] = o.BottomRightY
	toSerialize["content"] = o.Content
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *OCRAsideTextBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"top_left_x",
		"top_left_y",
		"bottom_right_x",
		"bottom_right_y",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOCRAsideTextBlock := _OCRAsideTextBlock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOCRAsideTextBlock)

	if err != nil {
		return err
	}

	*o = OCRAsideTextBlock(varOCRAsideTextBlock)

	return err
}

type NullableOCRAsideTextBlock struct {
	value *OCRAsideTextBlock
	isSet bool
}

func (v NullableOCRAsideTextBlock) Get() *OCRAsideTextBlock {
	return v.value
}

func (v *NullableOCRAsideTextBlock) Set(val *OCRAsideTextBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableOCRAsideTextBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableOCRAsideTextBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOCRAsideTextBlock(val *OCRAsideTextBlock) *NullableOCRAsideTextBlock {
	return &NullableOCRAsideTextBlock{value: val, isSet: true}
}

func (v NullableOCRAsideTextBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOCRAsideTextBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


