/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DeploymentWorkerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentWorkerResponse{}

// DeploymentWorkerResponse struct for DeploymentWorkerResponse
type DeploymentWorkerResponse struct {
	// Worker name
	Name string `json:"name"`
	// When the worker first registered
	CreatedAt time.Time `json:"created_at"`
	// When the worker last registered
	UpdatedAt time.Time `json:"updated_at"`
}

type _DeploymentWorkerResponse DeploymentWorkerResponse

// NewDeploymentWorkerResponse instantiates a new DeploymentWorkerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentWorkerResponse(name string, createdAt time.Time, updatedAt time.Time) *DeploymentWorkerResponse {
	this := DeploymentWorkerResponse{}
	this.Name = name
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewDeploymentWorkerResponseWithDefaults instantiates a new DeploymentWorkerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentWorkerResponseWithDefaults() *DeploymentWorkerResponse {
	this := DeploymentWorkerResponse{}
	return &this
}

// GetName returns the Name field value
func (o *DeploymentWorkerResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeploymentWorkerResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeploymentWorkerResponse) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeploymentWorkerResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeploymentWorkerResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeploymentWorkerResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DeploymentWorkerResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DeploymentWorkerResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DeploymentWorkerResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o DeploymentWorkerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentWorkerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *DeploymentWorkerResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentWorkerResponse := _DeploymentWorkerResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentWorkerResponse)

	if err != nil {
		return err
	}

	*o = DeploymentWorkerResponse(varDeploymentWorkerResponse)

	return err
}

type NullableDeploymentWorkerResponse struct {
	value *DeploymentWorkerResponse
	isSet bool
}

func (v NullableDeploymentWorkerResponse) Get() *DeploymentWorkerResponse {
	return v.value
}

func (v *NullableDeploymentWorkerResponse) Set(val *DeploymentWorkerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentWorkerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentWorkerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentWorkerResponse(val *DeploymentWorkerResponse) *NullableDeploymentWorkerResponse {
	return &NullableDeploymentWorkerResponse{value: val, isSet: true}
}

func (v NullableDeploymentWorkerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentWorkerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


