/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the StreamEventSsePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamEventSsePayload{}

// StreamEventSsePayload struct for StreamEventSsePayload
type StreamEventSsePayload struct {
	Stream string `json:"stream"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Data Data3 `json:"data"`
	WorkflowContext StreamEventWorkflowContext `json:"workflow_context"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	BrokerSequence int32 `json:"broker_sequence"`
}

type _StreamEventSsePayload StreamEventSsePayload

// NewStreamEventSsePayload instantiates a new StreamEventSsePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamEventSsePayload(stream string, data Data3, workflowContext StreamEventWorkflowContext, brokerSequence int32) *StreamEventSsePayload {
	this := StreamEventSsePayload{}
	this.Stream = stream
	this.Data = data
	this.WorkflowContext = workflowContext
	this.BrokerSequence = brokerSequence
	return &this
}

// NewStreamEventSsePayloadWithDefaults instantiates a new StreamEventSsePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamEventSsePayloadWithDefaults() *StreamEventSsePayload {
	this := StreamEventSsePayload{}
	return &this
}

// GetStream returns the Stream field value
func (o *StreamEventSsePayload) GetStream() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stream
}

// GetStreamOk returns a tuple with the Stream field value
// and a boolean to check if the value has been set.
func (o *StreamEventSsePayload) GetStreamOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stream, true
}

// SetStream sets field value
func (o *StreamEventSsePayload) SetStream(v string) {
	o.Stream = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *StreamEventSsePayload) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamEventSsePayload) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *StreamEventSsePayload) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *StreamEventSsePayload) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetData returns the Data field value
func (o *StreamEventSsePayload) GetData() Data3 {
	if o == nil {
		var ret Data3
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *StreamEventSsePayload) GetDataOk() (*Data3, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *StreamEventSsePayload) SetData(v Data3) {
	o.Data = v
}

// GetWorkflowContext returns the WorkflowContext field value
func (o *StreamEventSsePayload) GetWorkflowContext() StreamEventWorkflowContext {
	if o == nil {
		var ret StreamEventWorkflowContext
		return ret
	}

	return o.WorkflowContext
}

// GetWorkflowContextOk returns a tuple with the WorkflowContext field value
// and a boolean to check if the value has been set.
func (o *StreamEventSsePayload) GetWorkflowContextOk() (*StreamEventWorkflowContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowContext, true
}

// SetWorkflowContext sets field value
func (o *StreamEventSsePayload) SetWorkflowContext(v StreamEventWorkflowContext) {
	o.WorkflowContext = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *StreamEventSsePayload) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamEventSsePayload) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *StreamEventSsePayload) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *StreamEventSsePayload) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetBrokerSequence returns the BrokerSequence field value
func (o *StreamEventSsePayload) GetBrokerSequence() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BrokerSequence
}

// GetBrokerSequenceOk returns a tuple with the BrokerSequence field value
// and a boolean to check if the value has been set.
func (o *StreamEventSsePayload) GetBrokerSequenceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrokerSequence, true
}

// SetBrokerSequence sets field value
func (o *StreamEventSsePayload) SetBrokerSequence(v int32) {
	o.BrokerSequence = v
}

func (o StreamEventSsePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamEventSsePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["stream"] = o.Stream
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	toSerialize["data"] = o.Data
	toSerialize["workflow_context"] = o.WorkflowContext
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["broker_sequence"] = o.BrokerSequence
	return toSerialize, nil
}

func (o *StreamEventSsePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"stream",
		"data",
		"workflow_context",
		"broker_sequence",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStreamEventSsePayload := _StreamEventSsePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStreamEventSsePayload)

	if err != nil {
		return err
	}

	*o = StreamEventSsePayload(varStreamEventSsePayload)

	return err
}

type NullableStreamEventSsePayload struct {
	value *StreamEventSsePayload
	isSet bool
}

func (v NullableStreamEventSsePayload) Get() *StreamEventSsePayload {
	return v.value
}

func (v *NullableStreamEventSsePayload) Set(val *StreamEventSsePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamEventSsePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamEventSsePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamEventSsePayload(val *StreamEventSsePayload) *NullableStreamEventSsePayload {
	return &NullableStreamEventSsePayload{value: val, isSet: true}
}

func (v NullableStreamEventSsePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamEventSsePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


