/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JSONPatchAppend type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JSONPatchAppend{}

// JSONPatchAppend struct for JSONPatchAppend
type JSONPatchAppend struct {
	// A JSON Pointer (RFC 6901) identifying the target location within the document. Can be a string path (e.g., '/foo/bar'), '/', '', or an empty list [] for root-level operations.
	Path string `json:"path"`
	// The value to use for the operation. A string to append to the existing value
	Value string `json:"value"`
	// 'append' is an extension for efficient string concatenation in streaming scenarios.
	Op string `json:"op"`
}

type _JSONPatchAppend JSONPatchAppend

// NewJSONPatchAppend instantiates a new JSONPatchAppend object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJSONPatchAppend(path string, value string, op string) *JSONPatchAppend {
	this := JSONPatchAppend{}
	this.Path = path
	this.Value = value
	this.Op = op
	return &this
}

// NewJSONPatchAppendWithDefaults instantiates a new JSONPatchAppend object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJSONPatchAppendWithDefaults() *JSONPatchAppend {
	this := JSONPatchAppend{}
	return &this
}

// GetPath returns the Path field value
func (o *JSONPatchAppend) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *JSONPatchAppend) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *JSONPatchAppend) SetPath(v string) {
	o.Path = v
}

// GetValue returns the Value field value
func (o *JSONPatchAppend) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *JSONPatchAppend) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *JSONPatchAppend) SetValue(v string) {
	o.Value = v
}

// GetOp returns the Op field value
func (o *JSONPatchAppend) GetOp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Op
}

// GetOpOk returns a tuple with the Op field value
// and a boolean to check if the value has been set.
func (o *JSONPatchAppend) GetOpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Op, true
}

// SetOp sets field value
func (o *JSONPatchAppend) SetOp(v string) {
	o.Op = v
}

func (o JSONPatchAppend) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JSONPatchAppend) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	toSerialize["value"] = o.Value
	toSerialize["op"] = o.Op
	return toSerialize, nil
}

func (o *JSONPatchAppend) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"value",
		"op",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJSONPatchAppend := _JSONPatchAppend{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJSONPatchAppend)

	if err != nil {
		return err
	}

	*o = JSONPatchAppend(varJSONPatchAppend)

	return err
}

type NullableJSONPatchAppend struct {
	value *JSONPatchAppend
	isSet bool
}

func (v NullableJSONPatchAppend) Get() *JSONPatchAppend {
	return v.value
}

func (v *NullableJSONPatchAppend) Set(val *JSONPatchAppend) {
	v.value = val
	v.isSet = true
}

func (v NullableJSONPatchAppend) IsSet() bool {
	return v.isSet
}

func (v *NullableJSONPatchAppend) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJSONPatchAppend(val *JSONPatchAppend) *NullableJSONPatchAppend {
	return &NullableJSONPatchAppend{value: val, isSet: true}
}

func (v NullableJSONPatchAppend) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJSONPatchAppend) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


