/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// checks if the AudioContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudioContent{}

// AudioContent Audio content for a message.
type AudioContent struct {
	Type string `json:"type"`
	Data string `json:"data"`
	MimeType string `json:"mimeType"`
	Annotations NullableAnnotations `json:"annotations,omitempty"`
	Meta map[string]interface{} `json:"_meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AudioContent AudioContent

// NewAudioContent instantiates a new AudioContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudioContent(type_ string, data string, mimeType string) *AudioContent {
	this := AudioContent{}
	this.Type = type_
	this.Data = data
	this.MimeType = mimeType
	return &this
}

// NewAudioContentWithDefaults instantiates a new AudioContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudioContentWithDefaults() *AudioContent {
	this := AudioContent{}
	return &this
}

// GetType returns the Type field value
func (o *AudioContent) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AudioContent) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AudioContent) SetType(v string) {
	o.Type = v
}

// GetData returns the Data field value
func (o *AudioContent) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AudioContent) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AudioContent) SetData(v string) {
	o.Data = v
}

// GetMimeType returns the MimeType field value
func (o *AudioContent) GetMimeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value
// and a boolean to check if the value has been set.
func (o *AudioContent) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MimeType, true
}

// SetMimeType sets field value
func (o *AudioContent) SetMimeType(v string) {
	o.MimeType = v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioContent) GetAnnotations() Annotations {
	if o == nil || IsNil(o.Annotations.Get()) {
		var ret Annotations
		return ret
	}
	return *o.Annotations.Get()
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioContent) GetAnnotationsOk() (*Annotations, bool) {
	if o == nil {
		return nil, false
	}
	return o.Annotations.Get(), o.Annotations.IsSet()
}

// HasAnnotations returns a boolean if a field has been set.
func (o *AudioContent) HasAnnotations() bool {
	if o != nil && o.Annotations.IsSet() {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given NullableAnnotations and assigns it to the Annotations field.
func (o *AudioContent) SetAnnotations(v Annotations) {
	o.Annotations.Set(&v)
}
// SetAnnotationsNil sets the value for Annotations to be an explicit nil
func (o *AudioContent) SetAnnotationsNil() {
	o.Annotations.Set(nil)
}

// UnsetAnnotations ensures that no value is present for Annotations, not even an explicit nil
func (o *AudioContent) UnsetAnnotations() {
	o.Annotations.Unset()
}

// GetMeta returns the Meta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioContent) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioContent) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *AudioContent) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *AudioContent) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o AudioContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudioContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["data"] = o.Data
	toSerialize["mimeType"] = o.MimeType
	if o.Annotations.IsSet() {
		toSerialize["annotations"] = o.Annotations.Get()
	}
	if o.Meta != nil {
		toSerialize["_meta"] = o.Meta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AudioContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"data",
		"mimeType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAudioContent := _AudioContent{}

	err = json.Unmarshal(data, &varAudioContent)

	if err != nil {
		return err
	}

	*o = AudioContent(varAudioContent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "data")
		delete(additionalProperties, "mimeType")
		delete(additionalProperties, "annotations")
		delete(additionalProperties, "_meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAudioContent struct {
	value *AudioContent
	isSet bool
}

func (v NullableAudioContent) Get() *AudioContent {
	return v.value
}

func (v *NullableAudioContent) Set(val *AudioContent) {
	v.value = val
	v.isSet = true
}

func (v NullableAudioContent) IsSet() bool {
	return v.isSet
}

func (v *NullableAudioContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudioContent(val *AudioContent) *NullableAudioContent {
	return &NullableAudioContent{value: val, isSet: true}
}

func (v NullableAudioContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudioContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


