/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthenticationConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthenticationConfiguration{}

// AuthenticationConfiguration struct for AuthenticationConfiguration
type AuthenticationConfiguration struct {
	Name string `json:"name"`
	AuthenticationType OutboundAuthenticationType `json:"authentication_type"`
	IsDefault *bool `json:"is_default,omitempty"`
}

type _AuthenticationConfiguration AuthenticationConfiguration

// NewAuthenticationConfiguration instantiates a new AuthenticationConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticationConfiguration(name string, authenticationType OutboundAuthenticationType) *AuthenticationConfiguration {
	this := AuthenticationConfiguration{}
	this.Name = name
	this.AuthenticationType = authenticationType
	var isDefault bool = false
	this.IsDefault = &isDefault
	return &this
}

// NewAuthenticationConfigurationWithDefaults instantiates a new AuthenticationConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticationConfigurationWithDefaults() *AuthenticationConfiguration {
	this := AuthenticationConfiguration{}
	var isDefault bool = false
	this.IsDefault = &isDefault
	return &this
}

// GetName returns the Name field value
func (o *AuthenticationConfiguration) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AuthenticationConfiguration) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AuthenticationConfiguration) SetName(v string) {
	o.Name = v
}

// GetAuthenticationType returns the AuthenticationType field value
func (o *AuthenticationConfiguration) GetAuthenticationType() OutboundAuthenticationType {
	if o == nil {
		var ret OutboundAuthenticationType
		return ret
	}

	return o.AuthenticationType
}

// GetAuthenticationTypeOk returns a tuple with the AuthenticationType field value
// and a boolean to check if the value has been set.
func (o *AuthenticationConfiguration) GetAuthenticationTypeOk() (*OutboundAuthenticationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationType, true
}

// SetAuthenticationType sets field value
func (o *AuthenticationConfiguration) SetAuthenticationType(v OutboundAuthenticationType) {
	o.AuthenticationType = v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *AuthenticationConfiguration) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticationConfiguration) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *AuthenticationConfiguration) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *AuthenticationConfiguration) SetIsDefault(v bool) {
	o.IsDefault = &v
}

func (o AuthenticationConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthenticationConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["authentication_type"] = o.AuthenticationType
	if !IsNil(o.IsDefault) {
		toSerialize["is_default"] = o.IsDefault
	}
	return toSerialize, nil
}

func (o *AuthenticationConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"authentication_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthenticationConfiguration := _AuthenticationConfiguration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varAuthenticationConfiguration)

	if err != nil {
		return err
	}

	*o = AuthenticationConfiguration(varAuthenticationConfiguration)

	return err
}

type NullableAuthenticationConfiguration struct {
	value *AuthenticationConfiguration
	isSet bool
}

func (v NullableAuthenticationConfiguration) Get() *AuthenticationConfiguration {
	return v.value
}

func (v *NullableAuthenticationConfiguration) Set(val *AuthenticationConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticationConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticationConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticationConfiguration(val *AuthenticationConfiguration) *NullableAuthenticationConfiguration {
	return &NullableAuthenticationConfiguration{value: val, isSet: true}
}

func (v NullableAuthenticationConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticationConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


