/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
)

// checks if the WorkflowExecutionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowExecutionRequest{}

// WorkflowExecutionRequest struct for WorkflowExecutionRequest
type WorkflowExecutionRequest struct {
	// Allows you to specify a custom execution ID. If not provided, a random ID will be generated.
	ExecutionId NullableString `json:"execution_id,omitempty"`
	// Output JSON schema of the query's model
	Input map[string]interface{} `json:"input,omitempty"`
	// Encoded input to the workflow, used when payload encoding is enabled.
	EncodedInput NullableNetworkEncodedInput `json:"encoded_input,omitempty"`
	// If true, wait for the workflow to complete and return the result directly.
	WaitForResult *bool `json:"wait_for_result,omitempty"`
	// Maximum time to wait for completion when wait_for_result is true.
	TimeoutSeconds NullableFloat32 `json:"timeout_seconds,omitempty"`
	CustomTracingAttributes map[string]string `json:"custom_tracing_attributes,omitempty"`
	// Deprecated. Use deployment_name instead.
	TaskQueue NullableString `json:"task_queue,omitempty"`
	// Name of the deployment to route this execution to
	DeploymentName NullableString `json:"deployment_name,omitempty"`
}

// NewWorkflowExecutionRequest instantiates a new WorkflowExecutionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowExecutionRequest() *WorkflowExecutionRequest {
	this := WorkflowExecutionRequest{}
	var waitForResult bool = false
	this.WaitForResult = &waitForResult
	return &this
}

// NewWorkflowExecutionRequestWithDefaults instantiates a new WorkflowExecutionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowExecutionRequestWithDefaults() *WorkflowExecutionRequest {
	this := WorkflowExecutionRequest{}
	var waitForResult bool = false
	this.WaitForResult = &waitForResult
	return &this
}

// GetExecutionId returns the ExecutionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowExecutionRequest) GetExecutionId() string {
	if o == nil || IsNil(o.ExecutionId.Get()) {
		var ret string
		return ret
	}
	return *o.ExecutionId.Get()
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowExecutionRequest) GetExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExecutionId.Get(), o.ExecutionId.IsSet()
}

// HasExecutionId returns a boolean if a field has been set.
func (o *WorkflowExecutionRequest) HasExecutionId() bool {
	if o != nil && o.ExecutionId.IsSet() {
		return true
	}

	return false
}

// SetExecutionId gets a reference to the given NullableString and assigns it to the ExecutionId field.
func (o *WorkflowExecutionRequest) SetExecutionId(v string) {
	o.ExecutionId.Set(&v)
}
// SetExecutionIdNil sets the value for ExecutionId to be an explicit nil
func (o *WorkflowExecutionRequest) SetExecutionIdNil() {
	o.ExecutionId.Set(nil)
}

// UnsetExecutionId ensures that no value is present for ExecutionId, not even an explicit nil
func (o *WorkflowExecutionRequest) UnsetExecutionId() {
	o.ExecutionId.Unset()
}

// GetInput returns the Input field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowExecutionRequest) GetInput() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowExecutionRequest) GetInputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Input) {
		return map[string]interface{}{}, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *WorkflowExecutionRequest) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given map[string]interface{} and assigns it to the Input field.
func (o *WorkflowExecutionRequest) SetInput(v map[string]interface{}) {
	o.Input = v
}

// GetEncodedInput returns the EncodedInput field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowExecutionRequest) GetEncodedInput() NetworkEncodedInput {
	if o == nil || IsNil(o.EncodedInput.Get()) {
		var ret NetworkEncodedInput
		return ret
	}
	return *o.EncodedInput.Get()
}

// GetEncodedInputOk returns a tuple with the EncodedInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowExecutionRequest) GetEncodedInputOk() (*NetworkEncodedInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.EncodedInput.Get(), o.EncodedInput.IsSet()
}

// HasEncodedInput returns a boolean if a field has been set.
func (o *WorkflowExecutionRequest) HasEncodedInput() bool {
	if o != nil && o.EncodedInput.IsSet() {
		return true
	}

	return false
}

// SetEncodedInput gets a reference to the given NullableNetworkEncodedInput and assigns it to the EncodedInput field.
func (o *WorkflowExecutionRequest) SetEncodedInput(v NetworkEncodedInput) {
	o.EncodedInput.Set(&v)
}
// SetEncodedInputNil sets the value for EncodedInput to be an explicit nil
func (o *WorkflowExecutionRequest) SetEncodedInputNil() {
	o.EncodedInput.Set(nil)
}

// UnsetEncodedInput ensures that no value is present for EncodedInput, not even an explicit nil
func (o *WorkflowExecutionRequest) UnsetEncodedInput() {
	o.EncodedInput.Unset()
}

// GetWaitForResult returns the WaitForResult field value if set, zero value otherwise.
func (o *WorkflowExecutionRequest) GetWaitForResult() bool {
	if o == nil || IsNil(o.WaitForResult) {
		var ret bool
		return ret
	}
	return *o.WaitForResult
}

// GetWaitForResultOk returns a tuple with the WaitForResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionRequest) GetWaitForResultOk() (*bool, bool) {
	if o == nil || IsNil(o.WaitForResult) {
		return nil, false
	}
	return o.WaitForResult, true
}

// HasWaitForResult returns a boolean if a field has been set.
func (o *WorkflowExecutionRequest) HasWaitForResult() bool {
	if o != nil && !IsNil(o.WaitForResult) {
		return true
	}

	return false
}

// SetWaitForResult gets a reference to the given bool and assigns it to the WaitForResult field.
func (o *WorkflowExecutionRequest) SetWaitForResult(v bool) {
	o.WaitForResult = &v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowExecutionRequest) GetTimeoutSeconds() float32 {
	if o == nil || IsNil(o.TimeoutSeconds.Get()) {
		var ret float32
		return ret
	}
	return *o.TimeoutSeconds.Get()
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowExecutionRequest) GetTimeoutSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeoutSeconds.Get(), o.TimeoutSeconds.IsSet()
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *WorkflowExecutionRequest) HasTimeoutSeconds() bool {
	if o != nil && o.TimeoutSeconds.IsSet() {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given NullableFloat32 and assigns it to the TimeoutSeconds field.
func (o *WorkflowExecutionRequest) SetTimeoutSeconds(v float32) {
	o.TimeoutSeconds.Set(&v)
}
// SetTimeoutSecondsNil sets the value for TimeoutSeconds to be an explicit nil
func (o *WorkflowExecutionRequest) SetTimeoutSecondsNil() {
	o.TimeoutSeconds.Set(nil)
}

// UnsetTimeoutSeconds ensures that no value is present for TimeoutSeconds, not even an explicit nil
func (o *WorkflowExecutionRequest) UnsetTimeoutSeconds() {
	o.TimeoutSeconds.Unset()
}

// GetCustomTracingAttributes returns the CustomTracingAttributes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowExecutionRequest) GetCustomTracingAttributes() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.CustomTracingAttributes
}

// GetCustomTracingAttributesOk returns a tuple with the CustomTracingAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowExecutionRequest) GetCustomTracingAttributesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.CustomTracingAttributes) {
		return map[string]string{}, false
	}
	return o.CustomTracingAttributes, true
}

// HasCustomTracingAttributes returns a boolean if a field has been set.
func (o *WorkflowExecutionRequest) HasCustomTracingAttributes() bool {
	if o != nil && !IsNil(o.CustomTracingAttributes) {
		return true
	}

	return false
}

// SetCustomTracingAttributes gets a reference to the given map[string]string and assigns it to the CustomTracingAttributes field.
func (o *WorkflowExecutionRequest) SetCustomTracingAttributes(v map[string]string) {
	o.CustomTracingAttributes = v
}

// GetTaskQueue returns the TaskQueue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowExecutionRequest) GetTaskQueue() string {
	if o == nil || IsNil(o.TaskQueue.Get()) {
		var ret string
		return ret
	}
	return *o.TaskQueue.Get()
}

// GetTaskQueueOk returns a tuple with the TaskQueue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowExecutionRequest) GetTaskQueueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskQueue.Get(), o.TaskQueue.IsSet()
}

// HasTaskQueue returns a boolean if a field has been set.
func (o *WorkflowExecutionRequest) HasTaskQueue() bool {
	if o != nil && o.TaskQueue.IsSet() {
		return true
	}

	return false
}

// SetTaskQueue gets a reference to the given NullableString and assigns it to the TaskQueue field.
func (o *WorkflowExecutionRequest) SetTaskQueue(v string) {
	o.TaskQueue.Set(&v)
}
// SetTaskQueueNil sets the value for TaskQueue to be an explicit nil
func (o *WorkflowExecutionRequest) SetTaskQueueNil() {
	o.TaskQueue.Set(nil)
}

// UnsetTaskQueue ensures that no value is present for TaskQueue, not even an explicit nil
func (o *WorkflowExecutionRequest) UnsetTaskQueue() {
	o.TaskQueue.Unset()
}

// GetDeploymentName returns the DeploymentName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowExecutionRequest) GetDeploymentName() string {
	if o == nil || IsNil(o.DeploymentName.Get()) {
		var ret string
		return ret
	}
	return *o.DeploymentName.Get()
}

// GetDeploymentNameOk returns a tuple with the DeploymentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowExecutionRequest) GetDeploymentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeploymentName.Get(), o.DeploymentName.IsSet()
}

// HasDeploymentName returns a boolean if a field has been set.
func (o *WorkflowExecutionRequest) HasDeploymentName() bool {
	if o != nil && o.DeploymentName.IsSet() {
		return true
	}

	return false
}

// SetDeploymentName gets a reference to the given NullableString and assigns it to the DeploymentName field.
func (o *WorkflowExecutionRequest) SetDeploymentName(v string) {
	o.DeploymentName.Set(&v)
}
// SetDeploymentNameNil sets the value for DeploymentName to be an explicit nil
func (o *WorkflowExecutionRequest) SetDeploymentNameNil() {
	o.DeploymentName.Set(nil)
}

// UnsetDeploymentName ensures that no value is present for DeploymentName, not even an explicit nil
func (o *WorkflowExecutionRequest) UnsetDeploymentName() {
	o.DeploymentName.Unset()
}

func (o WorkflowExecutionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowExecutionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ExecutionId.IsSet() {
		toSerialize["execution_id"] = o.ExecutionId.Get()
	}
	if o.Input != nil {
		toSerialize["input"] = o.Input
	}
	if o.EncodedInput.IsSet() {
		toSerialize["encoded_input"] = o.EncodedInput.Get()
	}
	if !IsNil(o.WaitForResult) {
		toSerialize["wait_for_result"] = o.WaitForResult
	}
	if o.TimeoutSeconds.IsSet() {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds.Get()
	}
	if o.CustomTracingAttributes != nil {
		toSerialize["custom_tracing_attributes"] = o.CustomTracingAttributes
	}
	if o.TaskQueue.IsSet() {
		toSerialize["task_queue"] = o.TaskQueue.Get()
	}
	if o.DeploymentName.IsSet() {
		toSerialize["deployment_name"] = o.DeploymentName.Get()
	}
	return toSerialize, nil
}

type NullableWorkflowExecutionRequest struct {
	value *WorkflowExecutionRequest
	isSet bool
}

func (v NullableWorkflowExecutionRequest) Get() *WorkflowExecutionRequest {
	return v.value
}

func (v *NullableWorkflowExecutionRequest) Set(val *WorkflowExecutionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowExecutionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowExecutionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowExecutionRequest(val *WorkflowExecutionRequest) *NullableWorkflowExecutionRequest {
	return &NullableWorkflowExecutionRequest{value: val, isSet: true}
}

func (v NullableWorkflowExecutionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowExecutionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


