/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
)

// checks if the StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response{}

// StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response struct for StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response
type StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response struct {
	// Filter by agent name
	Event NullableString `json:"event,omitempty"`
	Data *StreamEventSsePayload `json:"data,omitempty"`
	// Filter by agent name
	Id NullableString `json:"id,omitempty"`
	// Set before sending audio. Streaming delay updates are rejected after audio starts.
	Retry NullableInt32 `json:"retry,omitempty"`
}

// NewStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response instantiates a new StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response() *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response {
	this := StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response{}
	return &this
}

// NewStreamV1WorkflowsExecutionsExecutionIdStreamGet200ResponseWithDefaults instantiates a new StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamV1WorkflowsExecutionsExecutionIdStreamGet200ResponseWithDefaults() *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response {
	this := StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response{}
	return &this
}

// GetEvent returns the Event field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) GetEvent() string {
	if o == nil || IsNil(o.Event.Get()) {
		var ret string
		return ret
	}
	return *o.Event.Get()
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Event.Get(), o.Event.IsSet()
}

// HasEvent returns a boolean if a field has been set.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) HasEvent() bool {
	if o != nil && o.Event.IsSet() {
		return true
	}

	return false
}

// SetEvent gets a reference to the given NullableString and assigns it to the Event field.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) SetEvent(v string) {
	o.Event.Set(&v)
}
// SetEventNil sets the value for Event to be an explicit nil
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) SetEventNil() {
	o.Event.Set(nil)
}

// UnsetEvent ensures that no value is present for Event, not even an explicit nil
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) UnsetEvent() {
	o.Event.Unset()
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) GetData() StreamEventSsePayload {
	if o == nil || IsNil(o.Data) {
		var ret StreamEventSsePayload
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) GetDataOk() (*StreamEventSsePayload, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given StreamEventSsePayload and assigns it to the Data field.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) SetData(v StreamEventSsePayload) {
	o.Data = &v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) UnsetId() {
	o.Id.Unset()
}

// GetRetry returns the Retry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) GetRetry() int32 {
	if o == nil || IsNil(o.Retry.Get()) {
		var ret int32
		return ret
	}
	return *o.Retry.Get()
}

// GetRetryOk returns a tuple with the Retry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) GetRetryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Retry.Get(), o.Retry.IsSet()
}

// HasRetry returns a boolean if a field has been set.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) HasRetry() bool {
	if o != nil && o.Retry.IsSet() {
		return true
	}

	return false
}

// SetRetry gets a reference to the given NullableInt32 and assigns it to the Retry field.
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) SetRetry(v int32) {
	o.Retry.Set(&v)
}
// SetRetryNil sets the value for Retry to be an explicit nil
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) SetRetryNil() {
	o.Retry.Set(nil)
}

// UnsetRetry ensures that no value is present for Retry, not even an explicit nil
func (o *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) UnsetRetry() {
	o.Retry.Unset()
}

func (o StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Event.IsSet() {
		toSerialize["event"] = o.Event.Get()
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Retry.IsSet() {
		toSerialize["retry"] = o.Retry.Get()
	}
	return toSerialize, nil
}

type NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response struct {
	value *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response
	isSet bool
}

func (v NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) Get() *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response {
	return v.value
}

func (v *NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) Set(val *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response(val *StreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) *NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response {
	return &NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response{value: val, isSet: true}
}

func (v NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamV1WorkflowsExecutionsExecutionIdStreamGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


