/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VoiceListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoiceListResponse{}

// VoiceListResponse Schema for voice list response
type VoiceListResponse struct {
	Items []VoiceResponse `json:"items"`
	Total int32 `json:"total"`
	Page int32 `json:"page"`
	PageSize int32 `json:"page_size"`
	TotalPages int32 `json:"total_pages"`
}

type _VoiceListResponse VoiceListResponse

// NewVoiceListResponse instantiates a new VoiceListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoiceListResponse(items []VoiceResponse, total int32, page int32, pageSize int32, totalPages int32) *VoiceListResponse {
	this := VoiceListResponse{}
	this.Items = items
	this.Total = total
	this.Page = page
	this.PageSize = pageSize
	this.TotalPages = totalPages
	return &this
}

// NewVoiceListResponseWithDefaults instantiates a new VoiceListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoiceListResponseWithDefaults() *VoiceListResponse {
	this := VoiceListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *VoiceListResponse) GetItems() []VoiceResponse {
	if o == nil {
		var ret []VoiceResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *VoiceListResponse) GetItemsOk() ([]VoiceResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *VoiceListResponse) SetItems(v []VoiceResponse) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *VoiceListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *VoiceListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *VoiceListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *VoiceListResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *VoiceListResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *VoiceListResponse) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *VoiceListResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *VoiceListResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *VoiceListResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetTotalPages returns the TotalPages field value
func (o *VoiceListResponse) GetTotalPages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *VoiceListResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *VoiceListResponse) SetTotalPages(v int32) {
	o.TotalPages = v
}

func (o VoiceListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoiceListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["page_size"] = o.PageSize
	toSerialize["total_pages"] = o.TotalPages
	return toSerialize, nil
}

func (o *VoiceListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
		"page",
		"page_size",
		"total_pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoiceListResponse := _VoiceListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varVoiceListResponse)

	if err != nil {
		return err
	}

	*o = VoiceListResponse(varVoiceListResponse)

	return err
}

type NullableVoiceListResponse struct {
	value *VoiceListResponse
	isSet bool
}

func (v NullableVoiceListResponse) Get() *VoiceListResponse {
	return v.value
}

func (v *NullableVoiceListResponse) Set(val *VoiceListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVoiceListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVoiceListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoiceListResponse(val *VoiceListResponse) *NullableVoiceListResponse {
	return &NullableVoiceListResponse{value: val, isSet: true}
}

func (v NullableVoiceListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoiceListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


