/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseFieldDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseFieldDefinition{}

// BaseFieldDefinition struct for BaseFieldDefinition
type BaseFieldDefinition struct {
	Name string `json:"name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Group NullableString `json:"group,omitempty"`
	SupportedOperators []string `json:"supported_operators"`
}

type _BaseFieldDefinition BaseFieldDefinition

// NewBaseFieldDefinition instantiates a new BaseFieldDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseFieldDefinition(name string, label string, type_ string, supportedOperators []string) *BaseFieldDefinition {
	this := BaseFieldDefinition{}
	this.Name = name
	this.Label = label
	this.Type = type_
	this.SupportedOperators = supportedOperators
	return &this
}

// NewBaseFieldDefinitionWithDefaults instantiates a new BaseFieldDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseFieldDefinitionWithDefaults() *BaseFieldDefinition {
	this := BaseFieldDefinition{}
	return &this
}

// GetName returns the Name field value
func (o *BaseFieldDefinition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BaseFieldDefinition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BaseFieldDefinition) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value
func (o *BaseFieldDefinition) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *BaseFieldDefinition) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *BaseFieldDefinition) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value
func (o *BaseFieldDefinition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BaseFieldDefinition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BaseFieldDefinition) SetType(v string) {
	o.Type = v
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseFieldDefinition) GetGroup() string {
	if o == nil || IsNil(o.Group.Get()) {
		var ret string
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseFieldDefinition) GetGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *BaseFieldDefinition) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableString and assigns it to the Group field.
func (o *BaseFieldDefinition) SetGroup(v string) {
	o.Group.Set(&v)
}
// SetGroupNil sets the value for Group to be an explicit nil
func (o *BaseFieldDefinition) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *BaseFieldDefinition) UnsetGroup() {
	o.Group.Unset()
}

// GetSupportedOperators returns the SupportedOperators field value
func (o *BaseFieldDefinition) GetSupportedOperators() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SupportedOperators
}

// GetSupportedOperatorsOk returns a tuple with the SupportedOperators field value
// and a boolean to check if the value has been set.
func (o *BaseFieldDefinition) GetSupportedOperatorsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportedOperators, true
}

// SetSupportedOperators sets field value
func (o *BaseFieldDefinition) SetSupportedOperators(v []string) {
	o.SupportedOperators = v
}

func (o BaseFieldDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseFieldDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["label"] = o.Label
	toSerialize["type"] = o.Type
	if o.Group.IsSet() {
		toSerialize["group"] = o.Group.Get()
	}
	toSerialize["supported_operators"] = o.SupportedOperators
	return toSerialize, nil
}

func (o *BaseFieldDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"label",
		"type",
		"supported_operators",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseFieldDefinition := _BaseFieldDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varBaseFieldDefinition)

	if err != nil {
		return err
	}

	*o = BaseFieldDefinition(varBaseFieldDefinition)

	return err
}

type NullableBaseFieldDefinition struct {
	value *BaseFieldDefinition
	isSet bool
}

func (v NullableBaseFieldDefinition) Get() *BaseFieldDefinition {
	return v.value
}

func (v *NullableBaseFieldDefinition) Set(val *BaseFieldDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseFieldDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseFieldDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseFieldDefinition(val *BaseFieldDefinition) *NullableBaseFieldDefinition {
	return &NullableBaseFieldDefinition{value: val, isSet: true}
}

func (v NullableBaseFieldDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseFieldDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


