/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
)

// checks if the ChatCompletionFieldOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatCompletionFieldOptions{}

// ChatCompletionFieldOptions struct for ChatCompletionFieldOptions
type ChatCompletionFieldOptions struct {
	Options []ChatCompletionFieldOptionsOptionsInner `json:"options,omitempty"`
}

// NewChatCompletionFieldOptions instantiates a new ChatCompletionFieldOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatCompletionFieldOptions() *ChatCompletionFieldOptions {
	this := ChatCompletionFieldOptions{}
	return &this
}

// NewChatCompletionFieldOptionsWithDefaults instantiates a new ChatCompletionFieldOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatCompletionFieldOptionsWithDefaults() *ChatCompletionFieldOptions {
	this := ChatCompletionFieldOptions{}
	return &this
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatCompletionFieldOptions) GetOptions() []ChatCompletionFieldOptionsOptionsInner {
	if o == nil {
		var ret []ChatCompletionFieldOptionsOptionsInner
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatCompletionFieldOptions) GetOptionsOk() ([]ChatCompletionFieldOptionsOptionsInner, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *ChatCompletionFieldOptions) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []ChatCompletionFieldOptionsOptionsInner and assigns it to the Options field.
func (o *ChatCompletionFieldOptions) SetOptions(v []ChatCompletionFieldOptionsOptionsInner) {
	o.Options = v
}

func (o ChatCompletionFieldOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatCompletionFieldOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableChatCompletionFieldOptions struct {
	value *ChatCompletionFieldOptions
	isSet bool
}

func (v NullableChatCompletionFieldOptions) Get() *ChatCompletionFieldOptions {
	return v.value
}

func (v *NullableChatCompletionFieldOptions) Set(val *ChatCompletionFieldOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionFieldOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionFieldOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionFieldOptions(val *ChatCompletionFieldOptions) *NullableChatCompletionFieldOptions {
	return &NullableChatCompletionFieldOptions{value: val, isSet: true}
}

func (v NullableChatCompletionFieldOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionFieldOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


