/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// checks if the MCPToolCallResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPToolCallResponse{}

// MCPToolCallResponse Response from calling an MCP tool.  We override mcp_types.CallToolResult because: - Models only support `content`, not `structuredContent` at top level - Downstream consumers (le-chat, etc.) need structuredContent/isError/_meta via metadata  SYNC: Keep in sync with Harmattan (orchestrator) for harmonized tool result processing.
type MCPToolCallResponse struct {
	Content []Content5Inner `json:"content"`
	Metadata NullableMCPToolCallMetadata `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MCPToolCallResponse MCPToolCallResponse

// NewMCPToolCallResponse instantiates a new MCPToolCallResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMCPToolCallResponse(content []Content5Inner) *MCPToolCallResponse {
	this := MCPToolCallResponse{}
	this.Content = content
	return &this
}

// NewMCPToolCallResponseWithDefaults instantiates a new MCPToolCallResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPToolCallResponseWithDefaults() *MCPToolCallResponse {
	this := MCPToolCallResponse{}
	return &this
}

// GetContent returns the Content field value
func (o *MCPToolCallResponse) GetContent() []Content5Inner {
	if o == nil {
		var ret []Content5Inner
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *MCPToolCallResponse) GetContentOk() ([]Content5Inner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content, true
}

// SetContent sets field value
func (o *MCPToolCallResponse) SetContent(v []Content5Inner) {
	o.Content = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MCPToolCallResponse) GetMetadata() MCPToolCallMetadata {
	if o == nil || IsNil(o.Metadata.Get()) {
		var ret MCPToolCallMetadata
		return ret
	}
	return *o.Metadata.Get()
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MCPToolCallResponse) GetMetadataOk() (*MCPToolCallMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metadata.Get(), o.Metadata.IsSet()
}

// HasMetadata returns a boolean if a field has been set.
func (o *MCPToolCallResponse) HasMetadata() bool {
	if o != nil && o.Metadata.IsSet() {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given NullableMCPToolCallMetadata and assigns it to the Metadata field.
func (o *MCPToolCallResponse) SetMetadata(v MCPToolCallMetadata) {
	o.Metadata.Set(&v)
}
// SetMetadataNil sets the value for Metadata to be an explicit nil
func (o *MCPToolCallResponse) SetMetadataNil() {
	o.Metadata.Set(nil)
}

// UnsetMetadata ensures that no value is present for Metadata, not even an explicit nil
func (o *MCPToolCallResponse) UnsetMetadata() {
	o.Metadata.Unset()
}

func (o MCPToolCallResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPToolCallResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	if o.Metadata.IsSet() {
		toSerialize["metadata"] = o.Metadata.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MCPToolCallResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMCPToolCallResponse := _MCPToolCallResponse{}

	err = json.Unmarshal(data, &varMCPToolCallResponse)

	if err != nil {
		return err
	}

	*o = MCPToolCallResponse(varMCPToolCallResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "content")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMCPToolCallResponse struct {
	value *MCPToolCallResponse
	isSet bool
}

func (v NullableMCPToolCallResponse) Get() *MCPToolCallResponse {
	return v.value
}

func (v *NullableMCPToolCallResponse) Set(val *MCPToolCallResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPToolCallResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPToolCallResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMCPToolCallResponse(val *MCPToolCallResponse) *NullableMCPToolCallResponse {
	return &NullableMCPToolCallResponse{value: val, isSet: true}
}

func (v NullableMCPToolCallResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPToolCallResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


