/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TempoTraceScope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TempoTraceScope{}

// TempoTraceScope struct for TempoTraceScope
type TempoTraceScope struct {
	// The name of the span
	Name string `json:"name"`
}

type _TempoTraceScope TempoTraceScope

// NewTempoTraceScope instantiates a new TempoTraceScope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTempoTraceScope(name string) *TempoTraceScope {
	this := TempoTraceScope{}
	this.Name = name
	return &this
}

// NewTempoTraceScopeWithDefaults instantiates a new TempoTraceScope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTempoTraceScopeWithDefaults() *TempoTraceScope {
	this := TempoTraceScope{}
	return &this
}

// GetName returns the Name field value
func (o *TempoTraceScope) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TempoTraceScope) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TempoTraceScope) SetName(v string) {
	o.Name = v
}

func (o TempoTraceScope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TempoTraceScope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *TempoTraceScope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTempoTraceScope := _TempoTraceScope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varTempoTraceScope)

	if err != nil {
		return err
	}

	*o = TempoTraceScope(varTempoTraceScope)

	return err
}

type NullableTempoTraceScope struct {
	value *TempoTraceScope
	isSet bool
}

func (v NullableTempoTraceScope) Get() *TempoTraceScope {
	return v.value
}

func (v *NullableTempoTraceScope) Set(val *TempoTraceScope) {
	v.value = val
	v.isSet = true
}

func (v NullableTempoTraceScope) IsSet() bool {
	return v.isSet
}

func (v *NullableTempoTraceScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTempoTraceScope(val *TempoTraceScope) *NullableTempoTraceScope {
	return &NullableTempoTraceScope{value: val, isSet: true}
}

func (v NullableTempoTraceScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTempoTraceScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


