/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
)

// checks if the ConnectorMCPUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorMCPUpdate{}

// ConnectorMCPUpdate struct for ConnectorMCPUpdate
type ConnectorMCPUpdate struct {
	// The name of the connector.
	Name NullableString `json:"name,omitempty"`
	// The description of the connector.
	Description NullableString `json:"description,omitempty"`
	// The optional url of the icon you want to associate to the connector.
	IconUrl NullableString `json:"icon_url,omitempty"`
	// Optional system prompt for the connector.
	SystemPrompt NullableString `json:"system_prompt,omitempty"`
	// Optional new connection config.
	ConnectionConfig map[string]interface{} `json:"connection_config,omitempty"`
	// Optional new connection secrets
	ConnectionSecrets map[string]interface{} `json:"connection_secrets,omitempty"`
	// New server url for your mcp connector.
	Server NullableString `json:"server,omitempty"`
	// New headers for your mcp connector.
	Headers map[string]interface{} `json:"headers,omitempty"`
	// New authentication data for your mcp connector.
	AuthData NullableAuthData `json:"auth_data,omitempty"`
}

// NewConnectorMCPUpdate instantiates a new ConnectorMCPUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorMCPUpdate() *ConnectorMCPUpdate {
	this := ConnectorMCPUpdate{}
	return &this
}

// NewConnectorMCPUpdateWithDefaults instantiates a new ConnectorMCPUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorMCPUpdateWithDefaults() *ConnectorMCPUpdate {
	this := ConnectorMCPUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ConnectorMCPUpdate) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ConnectorMCPUpdate) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ConnectorMCPUpdate) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ConnectorMCPUpdate) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ConnectorMCPUpdate) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ConnectorMCPUpdate) UnsetDescription() {
	o.Description.Unset()
}

// GetIconUrl returns the IconUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetIconUrl() string {
	if o == nil || IsNil(o.IconUrl.Get()) {
		var ret string
		return ret
	}
	return *o.IconUrl.Get()
}

// GetIconUrlOk returns a tuple with the IconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetIconUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IconUrl.Get(), o.IconUrl.IsSet()
}

// HasIconUrl returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasIconUrl() bool {
	if o != nil && o.IconUrl.IsSet() {
		return true
	}

	return false
}

// SetIconUrl gets a reference to the given NullableString and assigns it to the IconUrl field.
func (o *ConnectorMCPUpdate) SetIconUrl(v string) {
	o.IconUrl.Set(&v)
}
// SetIconUrlNil sets the value for IconUrl to be an explicit nil
func (o *ConnectorMCPUpdate) SetIconUrlNil() {
	o.IconUrl.Set(nil)
}

// UnsetIconUrl ensures that no value is present for IconUrl, not even an explicit nil
func (o *ConnectorMCPUpdate) UnsetIconUrl() {
	o.IconUrl.Unset()
}

// GetSystemPrompt returns the SystemPrompt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetSystemPrompt() string {
	if o == nil || IsNil(o.SystemPrompt.Get()) {
		var ret string
		return ret
	}
	return *o.SystemPrompt.Get()
}

// GetSystemPromptOk returns a tuple with the SystemPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetSystemPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SystemPrompt.Get(), o.SystemPrompt.IsSet()
}

// HasSystemPrompt returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasSystemPrompt() bool {
	if o != nil && o.SystemPrompt.IsSet() {
		return true
	}

	return false
}

// SetSystemPrompt gets a reference to the given NullableString and assigns it to the SystemPrompt field.
func (o *ConnectorMCPUpdate) SetSystemPrompt(v string) {
	o.SystemPrompt.Set(&v)
}
// SetSystemPromptNil sets the value for SystemPrompt to be an explicit nil
func (o *ConnectorMCPUpdate) SetSystemPromptNil() {
	o.SystemPrompt.Set(nil)
}

// UnsetSystemPrompt ensures that no value is present for SystemPrompt, not even an explicit nil
func (o *ConnectorMCPUpdate) UnsetSystemPrompt() {
	o.SystemPrompt.Unset()
}

// GetConnectionConfig returns the ConnectionConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetConnectionConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ConnectionConfig
}

// GetConnectionConfigOk returns a tuple with the ConnectionConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetConnectionConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ConnectionConfig) {
		return map[string]interface{}{}, false
	}
	return o.ConnectionConfig, true
}

// HasConnectionConfig returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasConnectionConfig() bool {
	if o != nil && !IsNil(o.ConnectionConfig) {
		return true
	}

	return false
}

// SetConnectionConfig gets a reference to the given map[string]interface{} and assigns it to the ConnectionConfig field.
func (o *ConnectorMCPUpdate) SetConnectionConfig(v map[string]interface{}) {
	o.ConnectionConfig = v
}

// GetConnectionSecrets returns the ConnectionSecrets field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetConnectionSecrets() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ConnectionSecrets
}

// GetConnectionSecretsOk returns a tuple with the ConnectionSecrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetConnectionSecretsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ConnectionSecrets) {
		return map[string]interface{}{}, false
	}
	return o.ConnectionSecrets, true
}

// HasConnectionSecrets returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasConnectionSecrets() bool {
	if o != nil && !IsNil(o.ConnectionSecrets) {
		return true
	}

	return false
}

// SetConnectionSecrets gets a reference to the given map[string]interface{} and assigns it to the ConnectionSecrets field.
func (o *ConnectorMCPUpdate) SetConnectionSecrets(v map[string]interface{}) {
	o.ConnectionSecrets = v
}

// GetServer returns the Server field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetServer() string {
	if o == nil || IsNil(o.Server.Get()) {
		var ret string
		return ret
	}
	return *o.Server.Get()
}

// GetServerOk returns a tuple with the Server field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetServerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Server.Get(), o.Server.IsSet()
}

// HasServer returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasServer() bool {
	if o != nil && o.Server.IsSet() {
		return true
	}

	return false
}

// SetServer gets a reference to the given NullableString and assigns it to the Server field.
func (o *ConnectorMCPUpdate) SetServer(v string) {
	o.Server.Set(&v)
}
// SetServerNil sets the value for Server to be an explicit nil
func (o *ConnectorMCPUpdate) SetServerNil() {
	o.Server.Set(nil)
}

// UnsetServer ensures that no value is present for Server, not even an explicit nil
func (o *ConnectorMCPUpdate) UnsetServer() {
	o.Server.Unset()
}

// GetHeaders returns the Headers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetHeaders() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetHeadersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Headers) {
		return map[string]interface{}{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]interface{} and assigns it to the Headers field.
func (o *ConnectorMCPUpdate) SetHeaders(v map[string]interface{}) {
	o.Headers = v
}

// GetAuthData returns the AuthData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorMCPUpdate) GetAuthData() AuthData {
	if o == nil || IsNil(o.AuthData.Get()) {
		var ret AuthData
		return ret
	}
	return *o.AuthData.Get()
}

// GetAuthDataOk returns a tuple with the AuthData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorMCPUpdate) GetAuthDataOk() (*AuthData, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthData.Get(), o.AuthData.IsSet()
}

// HasAuthData returns a boolean if a field has been set.
func (o *ConnectorMCPUpdate) HasAuthData() bool {
	if o != nil && o.AuthData.IsSet() {
		return true
	}

	return false
}

// SetAuthData gets a reference to the given NullableAuthData and assigns it to the AuthData field.
func (o *ConnectorMCPUpdate) SetAuthData(v AuthData) {
	o.AuthData.Set(&v)
}
// SetAuthDataNil sets the value for AuthData to be an explicit nil
func (o *ConnectorMCPUpdate) SetAuthDataNil() {
	o.AuthData.Set(nil)
}

// UnsetAuthData ensures that no value is present for AuthData, not even an explicit nil
func (o *ConnectorMCPUpdate) UnsetAuthData() {
	o.AuthData.Unset()
}

func (o ConnectorMCPUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorMCPUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.IconUrl.IsSet() {
		toSerialize["icon_url"] = o.IconUrl.Get()
	}
	if o.SystemPrompt.IsSet() {
		toSerialize["system_prompt"] = o.SystemPrompt.Get()
	}
	if o.ConnectionConfig != nil {
		toSerialize["connection_config"] = o.ConnectionConfig
	}
	if o.ConnectionSecrets != nil {
		toSerialize["connection_secrets"] = o.ConnectionSecrets
	}
	if o.Server.IsSet() {
		toSerialize["server"] = o.Server.Get()
	}
	if o.Headers != nil {
		toSerialize["headers"] = o.Headers
	}
	if o.AuthData.IsSet() {
		toSerialize["auth_data"] = o.AuthData.Get()
	}
	return toSerialize, nil
}

type NullableConnectorMCPUpdate struct {
	value *ConnectorMCPUpdate
	isSet bool
}

func (v NullableConnectorMCPUpdate) Get() *ConnectorMCPUpdate {
	return v.value
}

func (v *NullableConnectorMCPUpdate) Set(val *ConnectorMCPUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorMCPUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorMCPUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorMCPUpdate(val *ConnectorMCPUpdate) *NullableConnectorMCPUpdate {
	return &NullableConnectorMCPUpdate{value: val, isSet: true}
}

func (v NullableConnectorMCPUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorMCPUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


