/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeploymentListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentListResponse{}

// DeploymentListResponse struct for DeploymentListResponse
type DeploymentListResponse struct {
	// List of deployments
	Deployments []DeploymentResponse `json:"deployments"`
}

type _DeploymentListResponse DeploymentListResponse

// NewDeploymentListResponse instantiates a new DeploymentListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentListResponse(deployments []DeploymentResponse) *DeploymentListResponse {
	this := DeploymentListResponse{}
	this.Deployments = deployments
	return &this
}

// NewDeploymentListResponseWithDefaults instantiates a new DeploymentListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentListResponseWithDefaults() *DeploymentListResponse {
	this := DeploymentListResponse{}
	return &this
}

// GetDeployments returns the Deployments field value
func (o *DeploymentListResponse) GetDeployments() []DeploymentResponse {
	if o == nil {
		var ret []DeploymentResponse
		return ret
	}

	return o.Deployments
}

// GetDeploymentsOk returns a tuple with the Deployments field value
// and a boolean to check if the value has been set.
func (o *DeploymentListResponse) GetDeploymentsOk() ([]DeploymentResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deployments, true
}

// SetDeployments sets field value
func (o *DeploymentListResponse) SetDeployments(v []DeploymentResponse) {
	o.Deployments = v
}

func (o DeploymentListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deployments"] = o.Deployments
	return toSerialize, nil
}

func (o *DeploymentListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentListResponse := _DeploymentListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varDeploymentListResponse)

	if err != nil {
		return err
	}

	*o = DeploymentListResponse(varDeploymentListResponse)

	return err
}

type NullableDeploymentListResponse struct {
	value *DeploymentListResponse
	isSet bool
}

func (v NullableDeploymentListResponse) Get() *DeploymentListResponse {
	return v.value
}

func (v *NullableDeploymentListResponse) Set(val *DeploymentListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentListResponse(val *DeploymentListResponse) *NullableDeploymentListResponse {
	return &NullableDeploymentListResponse{value: val, isSet: true}
}

func (v NullableDeploymentListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


