/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)


// Value1 The value of the attribute
type Value1 struct {
	TempoTraceAttributeBoolValue *TempoTraceAttributeBoolValue
	TempoTraceAttributeIntValue *TempoTraceAttributeIntValue
	TempoTraceAttributeStringValue *TempoTraceAttributeStringValue
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Value1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into TempoTraceAttributeBoolValue
	err = json.Unmarshal(data, &dst.TempoTraceAttributeBoolValue);
	if err == nil {
		jsonTempoTraceAttributeBoolValue, _ := json.Marshal(dst.TempoTraceAttributeBoolValue)
		if string(jsonTempoTraceAttributeBoolValue) == "{}" { // empty struct
			dst.TempoTraceAttributeBoolValue = nil
		} else {
			return nil // data stored in dst.TempoTraceAttributeBoolValue, return on the first match
		}
	} else {
		dst.TempoTraceAttributeBoolValue = nil
	}

	// try to unmarshal JSON data into TempoTraceAttributeIntValue
	err = json.Unmarshal(data, &dst.TempoTraceAttributeIntValue);
	if err == nil {
		jsonTempoTraceAttributeIntValue, _ := json.Marshal(dst.TempoTraceAttributeIntValue)
		if string(jsonTempoTraceAttributeIntValue) == "{}" { // empty struct
			dst.TempoTraceAttributeIntValue = nil
		} else {
			return nil // data stored in dst.TempoTraceAttributeIntValue, return on the first match
		}
	} else {
		dst.TempoTraceAttributeIntValue = nil
	}

	// try to unmarshal JSON data into TempoTraceAttributeStringValue
	err = json.Unmarshal(data, &dst.TempoTraceAttributeStringValue);
	if err == nil {
		jsonTempoTraceAttributeStringValue, _ := json.Marshal(dst.TempoTraceAttributeStringValue)
		if string(jsonTempoTraceAttributeStringValue) == "{}" { // empty struct
			dst.TempoTraceAttributeStringValue = nil
		} else {
			return nil // data stored in dst.TempoTraceAttributeStringValue, return on the first match
		}
	} else {
		dst.TempoTraceAttributeStringValue = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Value1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Value1) MarshalJSON() ([]byte, error) {
	if src.TempoTraceAttributeBoolValue != nil {
		return json.Marshal(&src.TempoTraceAttributeBoolValue)
	}

	if src.TempoTraceAttributeIntValue != nil {
		return json.Marshal(&src.TempoTraceAttributeIntValue)
	}

	if src.TempoTraceAttributeStringValue != nil {
		return json.Marshal(&src.TempoTraceAttributeStringValue)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableValue1 struct {
	value *Value1
	isSet bool
}

func (v NullableValue1) Get() *Value1 {
	return v.value
}

func (v *NullableValue1) Set(val *Value1) {
	v.value = val
	v.isSet = true
}

func (v NullableValue1) IsSet() bool {
	return v.isSet
}

func (v *NullableValue1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValue1(val *Value1) *NullableValue1 {
	return &NullableValue1{value: val, isSet: true}
}

func (v NullableValue1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValue1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


