/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
)

// checks if the ConnectorsQueryFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorsQueryFilters{}

// ConnectorsQueryFilters struct for ConnectorsQueryFilters
type ConnectorsQueryFilters struct {
	// Filter for active connectors for a given user, workspace and organization.
	Active NullableBool `json:"active,omitempty"`
	// Fetch connection secrets.
	FetchConnectionSecrets *bool `json:"fetch_connection_secrets,omitempty"`
}

// NewConnectorsQueryFilters instantiates a new ConnectorsQueryFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorsQueryFilters() *ConnectorsQueryFilters {
	this := ConnectorsQueryFilters{}
	var fetchConnectionSecrets bool = false
	this.FetchConnectionSecrets = &fetchConnectionSecrets
	return &this
}

// NewConnectorsQueryFiltersWithDefaults instantiates a new ConnectorsQueryFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorsQueryFiltersWithDefaults() *ConnectorsQueryFilters {
	this := ConnectorsQueryFilters{}
	var fetchConnectionSecrets bool = false
	this.FetchConnectionSecrets = &fetchConnectionSecrets
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorsQueryFilters) GetActive() bool {
	if o == nil || IsNil(o.Active.Get()) {
		var ret bool
		return ret
	}
	return *o.Active.Get()
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorsQueryFilters) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Active.Get(), o.Active.IsSet()
}

// HasActive returns a boolean if a field has been set.
func (o *ConnectorsQueryFilters) HasActive() bool {
	if o != nil && o.Active.IsSet() {
		return true
	}

	return false
}

// SetActive gets a reference to the given NullableBool and assigns it to the Active field.
func (o *ConnectorsQueryFilters) SetActive(v bool) {
	o.Active.Set(&v)
}
// SetActiveNil sets the value for Active to be an explicit nil
func (o *ConnectorsQueryFilters) SetActiveNil() {
	o.Active.Set(nil)
}

// UnsetActive ensures that no value is present for Active, not even an explicit nil
func (o *ConnectorsQueryFilters) UnsetActive() {
	o.Active.Unset()
}

// GetFetchConnectionSecrets returns the FetchConnectionSecrets field value if set, zero value otherwise.
func (o *ConnectorsQueryFilters) GetFetchConnectionSecrets() bool {
	if o == nil || IsNil(o.FetchConnectionSecrets) {
		var ret bool
		return ret
	}
	return *o.FetchConnectionSecrets
}

// GetFetchConnectionSecretsOk returns a tuple with the FetchConnectionSecrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorsQueryFilters) GetFetchConnectionSecretsOk() (*bool, bool) {
	if o == nil || IsNil(o.FetchConnectionSecrets) {
		return nil, false
	}
	return o.FetchConnectionSecrets, true
}

// HasFetchConnectionSecrets returns a boolean if a field has been set.
func (o *ConnectorsQueryFilters) HasFetchConnectionSecrets() bool {
	if o != nil && !IsNil(o.FetchConnectionSecrets) {
		return true
	}

	return false
}

// SetFetchConnectionSecrets gets a reference to the given bool and assigns it to the FetchConnectionSecrets field.
func (o *ConnectorsQueryFilters) SetFetchConnectionSecrets(v bool) {
	o.FetchConnectionSecrets = &v
}

func (o ConnectorsQueryFilters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorsQueryFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Active.IsSet() {
		toSerialize["active"] = o.Active.Get()
	}
	if !IsNil(o.FetchConnectionSecrets) {
		toSerialize["fetch_connection_secrets"] = o.FetchConnectionSecrets
	}
	return toSerialize, nil
}

type NullableConnectorsQueryFilters struct {
	value *ConnectorsQueryFilters
	isSet bool
}

func (v NullableConnectorsQueryFilters) Get() *ConnectorsQueryFilters {
	return v.value
}

func (v *NullableConnectorsQueryFilters) Set(val *ConnectorsQueryFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorsQueryFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorsQueryFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorsQueryFilters(val *ConnectorsQueryFilters) *NullableConnectorsQueryFilters {
	return &NullableConnectorsQueryFilters{value: val, isSet: true}
}

func (v NullableConnectorsQueryFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorsQueryFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


