/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RealtimeTranscriptionClientMessage - struct for RealtimeTranscriptionClientMessage
type RealtimeTranscriptionClientMessage struct {
	RealtimeTranscriptionInputAudioAppend *RealtimeTranscriptionInputAudioAppend
	RealtimeTranscriptionInputAudioEnd *RealtimeTranscriptionInputAudioEnd
	RealtimeTranscriptionInputAudioFlush *RealtimeTranscriptionInputAudioFlush
	RealtimeTranscriptionSessionUpdateMessage *RealtimeTranscriptionSessionUpdateMessage
}

// RealtimeTranscriptionInputAudioAppendAsRealtimeTranscriptionClientMessage is a convenience function that returns RealtimeTranscriptionInputAudioAppend wrapped in RealtimeTranscriptionClientMessage
func RealtimeTranscriptionInputAudioAppendAsRealtimeTranscriptionClientMessage(v *RealtimeTranscriptionInputAudioAppend) RealtimeTranscriptionClientMessage {
	return RealtimeTranscriptionClientMessage{
		RealtimeTranscriptionInputAudioAppend: v,
	}
}

// RealtimeTranscriptionInputAudioEndAsRealtimeTranscriptionClientMessage is a convenience function that returns RealtimeTranscriptionInputAudioEnd wrapped in RealtimeTranscriptionClientMessage
func RealtimeTranscriptionInputAudioEndAsRealtimeTranscriptionClientMessage(v *RealtimeTranscriptionInputAudioEnd) RealtimeTranscriptionClientMessage {
	return RealtimeTranscriptionClientMessage{
		RealtimeTranscriptionInputAudioEnd: v,
	}
}

// RealtimeTranscriptionInputAudioFlushAsRealtimeTranscriptionClientMessage is a convenience function that returns RealtimeTranscriptionInputAudioFlush wrapped in RealtimeTranscriptionClientMessage
func RealtimeTranscriptionInputAudioFlushAsRealtimeTranscriptionClientMessage(v *RealtimeTranscriptionInputAudioFlush) RealtimeTranscriptionClientMessage {
	return RealtimeTranscriptionClientMessage{
		RealtimeTranscriptionInputAudioFlush: v,
	}
}

// RealtimeTranscriptionSessionUpdateMessageAsRealtimeTranscriptionClientMessage is a convenience function that returns RealtimeTranscriptionSessionUpdateMessage wrapped in RealtimeTranscriptionClientMessage
func RealtimeTranscriptionSessionUpdateMessageAsRealtimeTranscriptionClientMessage(v *RealtimeTranscriptionSessionUpdateMessage) RealtimeTranscriptionClientMessage {
	return RealtimeTranscriptionClientMessage{
		RealtimeTranscriptionSessionUpdateMessage: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RealtimeTranscriptionClientMessage) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into RealtimeTranscriptionInputAudioAppend
	err = newStrictDecoder(data).Decode(&dst.RealtimeTranscriptionInputAudioAppend)
	if err == nil {
		jsonRealtimeTranscriptionInputAudioAppend, _ := json.Marshal(dst.RealtimeTranscriptionInputAudioAppend)
		if string(jsonRealtimeTranscriptionInputAudioAppend) == "{}" { // empty struct
			dst.RealtimeTranscriptionInputAudioAppend = nil
		} else {
			if err = validator.Validate(dst.RealtimeTranscriptionInputAudioAppend); err != nil {
				dst.RealtimeTranscriptionInputAudioAppend = nil
			} else {
				match++
			}
		}
	} else {
		dst.RealtimeTranscriptionInputAudioAppend = nil
	}

	// try to unmarshal data into RealtimeTranscriptionInputAudioEnd
	err = newStrictDecoder(data).Decode(&dst.RealtimeTranscriptionInputAudioEnd)
	if err == nil {
		jsonRealtimeTranscriptionInputAudioEnd, _ := json.Marshal(dst.RealtimeTranscriptionInputAudioEnd)
		if string(jsonRealtimeTranscriptionInputAudioEnd) == "{}" { // empty struct
			dst.RealtimeTranscriptionInputAudioEnd = nil
		} else {
			if err = validator.Validate(dst.RealtimeTranscriptionInputAudioEnd); err != nil {
				dst.RealtimeTranscriptionInputAudioEnd = nil
			} else {
				match++
			}
		}
	} else {
		dst.RealtimeTranscriptionInputAudioEnd = nil
	}

	// try to unmarshal data into RealtimeTranscriptionInputAudioFlush
	err = newStrictDecoder(data).Decode(&dst.RealtimeTranscriptionInputAudioFlush)
	if err == nil {
		jsonRealtimeTranscriptionInputAudioFlush, _ := json.Marshal(dst.RealtimeTranscriptionInputAudioFlush)
		if string(jsonRealtimeTranscriptionInputAudioFlush) == "{}" { // empty struct
			dst.RealtimeTranscriptionInputAudioFlush = nil
		} else {
			if err = validator.Validate(dst.RealtimeTranscriptionInputAudioFlush); err != nil {
				dst.RealtimeTranscriptionInputAudioFlush = nil
			} else {
				match++
			}
		}
	} else {
		dst.RealtimeTranscriptionInputAudioFlush = nil
	}

	// try to unmarshal data into RealtimeTranscriptionSessionUpdateMessage
	err = newStrictDecoder(data).Decode(&dst.RealtimeTranscriptionSessionUpdateMessage)
	if err == nil {
		jsonRealtimeTranscriptionSessionUpdateMessage, _ := json.Marshal(dst.RealtimeTranscriptionSessionUpdateMessage)
		if string(jsonRealtimeTranscriptionSessionUpdateMessage) == "{}" { // empty struct
			dst.RealtimeTranscriptionSessionUpdateMessage = nil
		} else {
			if err = validator.Validate(dst.RealtimeTranscriptionSessionUpdateMessage); err != nil {
				dst.RealtimeTranscriptionSessionUpdateMessage = nil
			} else {
				match++
			}
		}
	} else {
		dst.RealtimeTranscriptionSessionUpdateMessage = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.RealtimeTranscriptionInputAudioAppend = nil
		dst.RealtimeTranscriptionInputAudioEnd = nil
		dst.RealtimeTranscriptionInputAudioFlush = nil
		dst.RealtimeTranscriptionSessionUpdateMessage = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RealtimeTranscriptionClientMessage)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(RealtimeTranscriptionClientMessage): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(RealtimeTranscriptionClientMessage)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RealtimeTranscriptionClientMessage) MarshalJSON() ([]byte, error) {
	if src.RealtimeTranscriptionInputAudioAppend != nil {
		return json.Marshal(&src.RealtimeTranscriptionInputAudioAppend)
	}

	if src.RealtimeTranscriptionInputAudioEnd != nil {
		return json.Marshal(&src.RealtimeTranscriptionInputAudioEnd)
	}

	if src.RealtimeTranscriptionInputAudioFlush != nil {
		return json.Marshal(&src.RealtimeTranscriptionInputAudioFlush)
	}

	if src.RealtimeTranscriptionSessionUpdateMessage != nil {
		return json.Marshal(&src.RealtimeTranscriptionSessionUpdateMessage)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RealtimeTranscriptionClientMessage) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.RealtimeTranscriptionInputAudioAppend != nil {
		return obj.RealtimeTranscriptionInputAudioAppend
	}

	if obj.RealtimeTranscriptionInputAudioEnd != nil {
		return obj.RealtimeTranscriptionInputAudioEnd
	}

	if obj.RealtimeTranscriptionInputAudioFlush != nil {
		return obj.RealtimeTranscriptionInputAudioFlush
	}

	if obj.RealtimeTranscriptionSessionUpdateMessage != nil {
		return obj.RealtimeTranscriptionSessionUpdateMessage
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RealtimeTranscriptionClientMessage) GetActualInstanceValue() (interface{}) {
	if obj.RealtimeTranscriptionInputAudioAppend != nil {
		return *obj.RealtimeTranscriptionInputAudioAppend
	}

	if obj.RealtimeTranscriptionInputAudioEnd != nil {
		return *obj.RealtimeTranscriptionInputAudioEnd
	}

	if obj.RealtimeTranscriptionInputAudioFlush != nil {
		return *obj.RealtimeTranscriptionInputAudioFlush
	}

	if obj.RealtimeTranscriptionSessionUpdateMessage != nil {
		return *obj.RealtimeTranscriptionSessionUpdateMessage
	}

	// all schemas are nil
	return nil
}

type NullableRealtimeTranscriptionClientMessage struct {
	value *RealtimeTranscriptionClientMessage
	isSet bool
}

func (v NullableRealtimeTranscriptionClientMessage) Get() *RealtimeTranscriptionClientMessage {
	return v.value
}

func (v *NullableRealtimeTranscriptionClientMessage) Set(val *RealtimeTranscriptionClientMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableRealtimeTranscriptionClientMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableRealtimeTranscriptionClientMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealtimeTranscriptionClientMessage(val *RealtimeTranscriptionClientMessage) *NullableRealtimeTranscriptionClientMessage {
	return &NullableRealtimeTranscriptionClientMessage{value: val, isSet: true}
}

func (v NullableRealtimeTranscriptionClientMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealtimeTranscriptionClientMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


