/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// ConversationSource the model 'ConversationSource'
type ConversationSource string

// List of ConversationSource
const (
	CONVERSATIONSOURCE_EXPLORER ConversationSource = "EXPLORER"
	CONVERSATIONSOURCE_UPLOADED_FILE ConversationSource = "UPLOADED_FILE"
	CONVERSATIONSOURCE_DIRECT_INPUT ConversationSource = "DIRECT_INPUT"
	CONVERSATIONSOURCE_PLAYGROUND ConversationSource = "PLAYGROUND"
)

// All allowed values of ConversationSource enum
var AllowedConversationSourceEnumValues = []ConversationSource{
	"EXPLORER",
	"UPLOADED_FILE",
	"DIRECT_INPUT",
	"PLAYGROUND",
}

func (v *ConversationSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ConversationSource(value)
	for _, existing := range AllowedConversationSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ConversationSource", value)
}

// NewConversationSourceFromValue returns a pointer to a valid ConversationSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewConversationSourceFromValue(v string) (*ConversationSource, error) {
	ev := ConversationSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ConversationSource: valid values are %v", v, AllowedConversationSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ConversationSource) IsValid() bool {
	for _, existing := range AllowedConversationSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ConversationSource value
func (v ConversationSource) Ptr() *ConversationSource {
	return &v
}

type NullableConversationSource struct {
	value *ConversationSource
	isSet bool
}

func (v NullableConversationSource) Get() *ConversationSource {
	return v.value
}

func (v *NullableConversationSource) Set(val *ConversationSource) {
	v.value = val
	v.isSet = true
}

func (v NullableConversationSource) IsSet() bool {
	return v.isSet
}

func (v *NullableConversationSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConversationSource(val *ConversationSource) *NullableConversationSource {
	return &NullableConversationSource{value: val, isSet: true}
}

func (v NullableConversationSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConversationSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

