/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ValueInner - struct for ValueInner
type ValueInner struct {
	JSONPatchAdd *JSONPatchAdd
	JSONPatchAppend *JSONPatchAppend
	JSONPatchRemove *JSONPatchRemove
	JSONPatchReplace *JSONPatchReplace
}

// JSONPatchAddAsValueInner is a convenience function that returns JSONPatchAdd wrapped in ValueInner
func JSONPatchAddAsValueInner(v *JSONPatchAdd) ValueInner {
	return ValueInner{
		JSONPatchAdd: v,
	}
}

// JSONPatchAppendAsValueInner is a convenience function that returns JSONPatchAppend wrapped in ValueInner
func JSONPatchAppendAsValueInner(v *JSONPatchAppend) ValueInner {
	return ValueInner{
		JSONPatchAppend: v,
	}
}

// JSONPatchRemoveAsValueInner is a convenience function that returns JSONPatchRemove wrapped in ValueInner
func JSONPatchRemoveAsValueInner(v *JSONPatchRemove) ValueInner {
	return ValueInner{
		JSONPatchRemove: v,
	}
}

// JSONPatchReplaceAsValueInner is a convenience function that returns JSONPatchReplace wrapped in ValueInner
func JSONPatchReplaceAsValueInner(v *JSONPatchReplace) ValueInner {
	return ValueInner{
		JSONPatchReplace: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ValueInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into JSONPatchAdd
	err = newStrictDecoder(data).Decode(&dst.JSONPatchAdd)
	if err == nil {
		jsonJSONPatchAdd, _ := json.Marshal(dst.JSONPatchAdd)
		if string(jsonJSONPatchAdd) == "{}" { // empty struct
			dst.JSONPatchAdd = nil
		} else {
			if err = validator.Validate(dst.JSONPatchAdd); err != nil {
				dst.JSONPatchAdd = nil
			} else {
				match++
			}
		}
	} else {
		dst.JSONPatchAdd = nil
	}

	// try to unmarshal data into JSONPatchAppend
	err = newStrictDecoder(data).Decode(&dst.JSONPatchAppend)
	if err == nil {
		jsonJSONPatchAppend, _ := json.Marshal(dst.JSONPatchAppend)
		if string(jsonJSONPatchAppend) == "{}" { // empty struct
			dst.JSONPatchAppend = nil
		} else {
			if err = validator.Validate(dst.JSONPatchAppend); err != nil {
				dst.JSONPatchAppend = nil
			} else {
				match++
			}
		}
	} else {
		dst.JSONPatchAppend = nil
	}

	// try to unmarshal data into JSONPatchRemove
	err = newStrictDecoder(data).Decode(&dst.JSONPatchRemove)
	if err == nil {
		jsonJSONPatchRemove, _ := json.Marshal(dst.JSONPatchRemove)
		if string(jsonJSONPatchRemove) == "{}" { // empty struct
			dst.JSONPatchRemove = nil
		} else {
			if err = validator.Validate(dst.JSONPatchRemove); err != nil {
				dst.JSONPatchRemove = nil
			} else {
				match++
			}
		}
	} else {
		dst.JSONPatchRemove = nil
	}

	// try to unmarshal data into JSONPatchReplace
	err = newStrictDecoder(data).Decode(&dst.JSONPatchReplace)
	if err == nil {
		jsonJSONPatchReplace, _ := json.Marshal(dst.JSONPatchReplace)
		if string(jsonJSONPatchReplace) == "{}" { // empty struct
			dst.JSONPatchReplace = nil
		} else {
			if err = validator.Validate(dst.JSONPatchReplace); err != nil {
				dst.JSONPatchReplace = nil
			} else {
				match++
			}
		}
	} else {
		dst.JSONPatchReplace = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.JSONPatchAdd = nil
		dst.JSONPatchAppend = nil
		dst.JSONPatchRemove = nil
		dst.JSONPatchReplace = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ValueInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(ValueInner): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(ValueInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ValueInner) MarshalJSON() ([]byte, error) {
	if src.JSONPatchAdd != nil {
		return json.Marshal(&src.JSONPatchAdd)
	}

	if src.JSONPatchAppend != nil {
		return json.Marshal(&src.JSONPatchAppend)
	}

	if src.JSONPatchRemove != nil {
		return json.Marshal(&src.JSONPatchRemove)
	}

	if src.JSONPatchReplace != nil {
		return json.Marshal(&src.JSONPatchReplace)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ValueInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.JSONPatchAdd != nil {
		return obj.JSONPatchAdd
	}

	if obj.JSONPatchAppend != nil {
		return obj.JSONPatchAppend
	}

	if obj.JSONPatchRemove != nil {
		return obj.JSONPatchRemove
	}

	if obj.JSONPatchReplace != nil {
		return obj.JSONPatchReplace
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ValueInner) GetActualInstanceValue() (interface{}) {
	if obj.JSONPatchAdd != nil {
		return *obj.JSONPatchAdd
	}

	if obj.JSONPatchAppend != nil {
		return *obj.JSONPatchAppend
	}

	if obj.JSONPatchRemove != nil {
		return *obj.JSONPatchRemove
	}

	if obj.JSONPatchReplace != nil {
		return *obj.JSONPatchReplace
	}

	// all schemas are nil
	return nil
}

type NullableValueInner struct {
	value *ValueInner
	isSet bool
}

func (v NullableValueInner) Get() *ValueInner {
	return v.value
}

func (v *NullableValueInner) Set(val *ValueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableValueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableValueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValueInner(val *ValueInner) *NullableValueInner {
	return &NullableValueInner{value: val, isSet: true}
}

func (v NullableValueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


