/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowExecutionContinuedAsNewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowExecutionContinuedAsNewResponse{}

// WorkflowExecutionContinuedAsNewResponse Emitted when a workflow continues as a new execution.  This occurs when a workflow uses continue-as-new to reset its history while maintaining logical continuity.
type WorkflowExecutionContinuedAsNewResponse struct {
	// Unique identifier for this event instance.
	EventId string `json:"event_id"`
	// Unix timestamp in nanoseconds when the event was created.
	EventTimestamp int32 `json:"event_timestamp"`
	// Execution ID of the root workflow that initiated this execution chain.
	RootWorkflowExecId string `json:"root_workflow_exec_id"`
	// Execution ID of the parent workflow that initiated this execution. If this is a root workflow, this field is not set.
	ParentWorkflowExecId NullableString `json:"parent_workflow_exec_id"`
	// Execution ID of the workflow that emitted this event.
	WorkflowExecId string `json:"workflow_exec_id"`
	// Run ID of the workflow execution. Changes on continue-as-new while workflow_exec_id stays the same.
	WorkflowRunId string `json:"workflow_run_id"`
	// The registered name of the workflow that emitted this event.
	WorkflowName string `json:"workflow_name"`
	// Event type discriminator.
	EventType string `json:"event_type"`
	// Event-specific attributes.
	Attributes WorkflowExecutionContinuedAsNewAttributesResponse `json:"attributes"`
}

type _WorkflowExecutionContinuedAsNewResponse WorkflowExecutionContinuedAsNewResponse

// NewWorkflowExecutionContinuedAsNewResponse instantiates a new WorkflowExecutionContinuedAsNewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowExecutionContinuedAsNewResponse(eventId string, eventTimestamp int32, rootWorkflowExecId string, parentWorkflowExecId NullableString, workflowExecId string, workflowRunId string, workflowName string, eventType string, attributes WorkflowExecutionContinuedAsNewAttributesResponse) *WorkflowExecutionContinuedAsNewResponse {
	this := WorkflowExecutionContinuedAsNewResponse{}
	this.EventId = eventId
	this.EventTimestamp = eventTimestamp
	this.RootWorkflowExecId = rootWorkflowExecId
	this.ParentWorkflowExecId = parentWorkflowExecId
	this.WorkflowExecId = workflowExecId
	this.WorkflowRunId = workflowRunId
	this.WorkflowName = workflowName
	this.EventType = eventType
	this.Attributes = attributes
	return &this
}

// NewWorkflowExecutionContinuedAsNewResponseWithDefaults instantiates a new WorkflowExecutionContinuedAsNewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowExecutionContinuedAsNewResponseWithDefaults() *WorkflowExecutionContinuedAsNewResponse {
	this := WorkflowExecutionContinuedAsNewResponse{}
	var eventType string = "WORKFLOW_EXECUTION_CONTINUED_AS_NEW"
	this.EventType = eventType
	return &this
}

// GetEventId returns the EventId field value
func (o *WorkflowExecutionContinuedAsNewResponse) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionContinuedAsNewResponse) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetEventId(v string) {
	o.EventId = v
}

// GetEventTimestamp returns the EventTimestamp field value
func (o *WorkflowExecutionContinuedAsNewResponse) GetEventTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventTimestamp
}

// GetEventTimestampOk returns a tuple with the EventTimestamp field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionContinuedAsNewResponse) GetEventTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventTimestamp, true
}

// SetEventTimestamp sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetEventTimestamp(v int32) {
	o.EventTimestamp = v
}

// GetRootWorkflowExecId returns the RootWorkflowExecId field value
func (o *WorkflowExecutionContinuedAsNewResponse) GetRootWorkflowExecId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootWorkflowExecId
}

// GetRootWorkflowExecIdOk returns a tuple with the RootWorkflowExecId field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionContinuedAsNewResponse) GetRootWorkflowExecIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootWorkflowExecId, true
}

// SetRootWorkflowExecId sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetRootWorkflowExecId(v string) {
	o.RootWorkflowExecId = v
}

// GetParentWorkflowExecId returns the ParentWorkflowExecId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkflowExecutionContinuedAsNewResponse) GetParentWorkflowExecId() string {
	if o == nil || o.ParentWorkflowExecId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ParentWorkflowExecId.Get()
}

// GetParentWorkflowExecIdOk returns a tuple with the ParentWorkflowExecId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowExecutionContinuedAsNewResponse) GetParentWorkflowExecIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentWorkflowExecId.Get(), o.ParentWorkflowExecId.IsSet()
}

// SetParentWorkflowExecId sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetParentWorkflowExecId(v string) {
	o.ParentWorkflowExecId.Set(&v)
}

// GetWorkflowExecId returns the WorkflowExecId field value
func (o *WorkflowExecutionContinuedAsNewResponse) GetWorkflowExecId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowExecId
}

// GetWorkflowExecIdOk returns a tuple with the WorkflowExecId field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionContinuedAsNewResponse) GetWorkflowExecIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowExecId, true
}

// SetWorkflowExecId sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetWorkflowExecId(v string) {
	o.WorkflowExecId = v
}

// GetWorkflowRunId returns the WorkflowRunId field value
func (o *WorkflowExecutionContinuedAsNewResponse) GetWorkflowRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowRunId
}

// GetWorkflowRunIdOk returns a tuple with the WorkflowRunId field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionContinuedAsNewResponse) GetWorkflowRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowRunId, true
}

// SetWorkflowRunId sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetWorkflowRunId(v string) {
	o.WorkflowRunId = v
}

// GetWorkflowName returns the WorkflowName field value
func (o *WorkflowExecutionContinuedAsNewResponse) GetWorkflowName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowName
}

// GetWorkflowNameOk returns a tuple with the WorkflowName field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionContinuedAsNewResponse) GetWorkflowNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowName, true
}

// SetWorkflowName sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetWorkflowName(v string) {
	o.WorkflowName = v
}

// GetEventType returns the EventType field value
func (o *WorkflowExecutionContinuedAsNewResponse) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionContinuedAsNewResponse) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetEventType(v string) {
	o.EventType = v
}

// GetAttributes returns the Attributes field value
func (o *WorkflowExecutionContinuedAsNewResponse) GetAttributes() WorkflowExecutionContinuedAsNewAttributesResponse {
	if o == nil {
		var ret WorkflowExecutionContinuedAsNewAttributesResponse
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionContinuedAsNewResponse) GetAttributesOk() (*WorkflowExecutionContinuedAsNewAttributesResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *WorkflowExecutionContinuedAsNewResponse) SetAttributes(v WorkflowExecutionContinuedAsNewAttributesResponse) {
	o.Attributes = v
}

func (o WorkflowExecutionContinuedAsNewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowExecutionContinuedAsNewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventId
	toSerialize["event_timestamp"] = o.EventTimestamp
	toSerialize["root_workflow_exec_id"] = o.RootWorkflowExecId
	toSerialize["parent_workflow_exec_id"] = o.ParentWorkflowExecId.Get()
	toSerialize["workflow_exec_id"] = o.WorkflowExecId
	toSerialize["workflow_run_id"] = o.WorkflowRunId
	toSerialize["workflow_name"] = o.WorkflowName
	toSerialize["event_type"] = o.EventType
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *WorkflowExecutionContinuedAsNewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"event_timestamp",
		"root_workflow_exec_id",
		"parent_workflow_exec_id",
		"workflow_exec_id",
		"workflow_run_id",
		"workflow_name",
		"event_type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowExecutionContinuedAsNewResponse := _WorkflowExecutionContinuedAsNewResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varWorkflowExecutionContinuedAsNewResponse)

	if err != nil {
		return err
	}

	*o = WorkflowExecutionContinuedAsNewResponse(varWorkflowExecutionContinuedAsNewResponse)

	return err
}

type NullableWorkflowExecutionContinuedAsNewResponse struct {
	value *WorkflowExecutionContinuedAsNewResponse
	isSet bool
}

func (v NullableWorkflowExecutionContinuedAsNewResponse) Get() *WorkflowExecutionContinuedAsNewResponse {
	return v.value
}

func (v *NullableWorkflowExecutionContinuedAsNewResponse) Set(val *WorkflowExecutionContinuedAsNewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowExecutionContinuedAsNewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowExecutionContinuedAsNewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowExecutionContinuedAsNewResponse(val *WorkflowExecutionContinuedAsNewResponse) *NullableWorkflowExecutionContinuedAsNewResponse {
	return &NullableWorkflowExecutionContinuedAsNewResponse{value: val, isSet: true}
}

func (v NullableWorkflowExecutionContinuedAsNewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowExecutionContinuedAsNewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


