/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the IntegrationsSchemasApiToolTool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationsSchemasApiToolTool{}

// IntegrationsSchemasApiToolTool struct for IntegrationsSchemasApiToolTool
type IntegrationsSchemasApiToolTool struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	SystemPrompt NullableString `json:"system_prompt,omitempty"`
	Locale NullableIntegrationsSchemasTurbineToolLocale `json:"locale,omitempty"`
	Jsonschema map[string]interface{} `json:"jsonschema,omitempty"`
	ExecutionConfig NullableExecutionConfig `json:"execution_config"`
	Visibility ResourceVisibility `json:"visibility"`
	CreatedAt time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
	Active NullableBool `json:"active,omitempty"`
}

type _IntegrationsSchemasApiToolTool IntegrationsSchemasApiToolTool

// NewIntegrationsSchemasApiToolTool instantiates a new IntegrationsSchemasApiToolTool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationsSchemasApiToolTool(id string, name string, description string, executionConfig NullableExecutionConfig, visibility ResourceVisibility, createdAt time.Time, modifiedAt time.Time) *IntegrationsSchemasApiToolTool {
	this := IntegrationsSchemasApiToolTool{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.ExecutionConfig = executionConfig
	this.Visibility = visibility
	this.CreatedAt = createdAt
	this.ModifiedAt = modifiedAt
	return &this
}

// NewIntegrationsSchemasApiToolToolWithDefaults instantiates a new IntegrationsSchemasApiToolTool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationsSchemasApiToolToolWithDefaults() *IntegrationsSchemasApiToolTool {
	this := IntegrationsSchemasApiToolTool{}
	return &this
}

// GetId returns the Id field value
func (o *IntegrationsSchemasApiToolTool) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IntegrationsSchemasApiToolTool) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IntegrationsSchemasApiToolTool) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *IntegrationsSchemasApiToolTool) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IntegrationsSchemasApiToolTool) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IntegrationsSchemasApiToolTool) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *IntegrationsSchemasApiToolTool) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *IntegrationsSchemasApiToolTool) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *IntegrationsSchemasApiToolTool) SetDescription(v string) {
	o.Description = v
}

// GetSystemPrompt returns the SystemPrompt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrationsSchemasApiToolTool) GetSystemPrompt() string {
	if o == nil || IsNil(o.SystemPrompt.Get()) {
		var ret string
		return ret
	}
	return *o.SystemPrompt.Get()
}

// GetSystemPromptOk returns a tuple with the SystemPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrationsSchemasApiToolTool) GetSystemPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SystemPrompt.Get(), o.SystemPrompt.IsSet()
}

// HasSystemPrompt returns a boolean if a field has been set.
func (o *IntegrationsSchemasApiToolTool) HasSystemPrompt() bool {
	if o != nil && o.SystemPrompt.IsSet() {
		return true
	}

	return false
}

// SetSystemPrompt gets a reference to the given NullableString and assigns it to the SystemPrompt field.
func (o *IntegrationsSchemasApiToolTool) SetSystemPrompt(v string) {
	o.SystemPrompt.Set(&v)
}
// SetSystemPromptNil sets the value for SystemPrompt to be an explicit nil
func (o *IntegrationsSchemasApiToolTool) SetSystemPromptNil() {
	o.SystemPrompt.Set(nil)
}

// UnsetSystemPrompt ensures that no value is present for SystemPrompt, not even an explicit nil
func (o *IntegrationsSchemasApiToolTool) UnsetSystemPrompt() {
	o.SystemPrompt.Unset()
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrationsSchemasApiToolTool) GetLocale() IntegrationsSchemasTurbineToolLocale {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret IntegrationsSchemasTurbineToolLocale
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrationsSchemasApiToolTool) GetLocaleOk() (*IntegrationsSchemasTurbineToolLocale, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *IntegrationsSchemasApiToolTool) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableIntegrationsSchemasTurbineToolLocale and assigns it to the Locale field.
func (o *IntegrationsSchemasApiToolTool) SetLocale(v IntegrationsSchemasTurbineToolLocale) {
	o.Locale.Set(&v)
}
// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *IntegrationsSchemasApiToolTool) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *IntegrationsSchemasApiToolTool) UnsetLocale() {
	o.Locale.Unset()
}

// GetJsonschema returns the Jsonschema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrationsSchemasApiToolTool) GetJsonschema() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Jsonschema
}

// GetJsonschemaOk returns a tuple with the Jsonschema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrationsSchemasApiToolTool) GetJsonschemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Jsonschema) {
		return map[string]interface{}{}, false
	}
	return o.Jsonschema, true
}

// HasJsonschema returns a boolean if a field has been set.
func (o *IntegrationsSchemasApiToolTool) HasJsonschema() bool {
	if o != nil && !IsNil(o.Jsonschema) {
		return true
	}

	return false
}

// SetJsonschema gets a reference to the given map[string]interface{} and assigns it to the Jsonschema field.
func (o *IntegrationsSchemasApiToolTool) SetJsonschema(v map[string]interface{}) {
	o.Jsonschema = v
}

// GetExecutionConfig returns the ExecutionConfig field value
// If the value is explicit nil, the zero value for ExecutionConfig will be returned
func (o *IntegrationsSchemasApiToolTool) GetExecutionConfig() ExecutionConfig {
	if o == nil || o.ExecutionConfig.Get() == nil {
		var ret ExecutionConfig
		return ret
	}

	return *o.ExecutionConfig.Get()
}

// GetExecutionConfigOk returns a tuple with the ExecutionConfig field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrationsSchemasApiToolTool) GetExecutionConfigOk() (*ExecutionConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExecutionConfig.Get(), o.ExecutionConfig.IsSet()
}

// SetExecutionConfig sets field value
func (o *IntegrationsSchemasApiToolTool) SetExecutionConfig(v ExecutionConfig) {
	o.ExecutionConfig.Set(&v)
}

// GetVisibility returns the Visibility field value
func (o *IntegrationsSchemasApiToolTool) GetVisibility() ResourceVisibility {
	if o == nil {
		var ret ResourceVisibility
		return ret
	}

	return o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value
// and a boolean to check if the value has been set.
func (o *IntegrationsSchemasApiToolTool) GetVisibilityOk() (*ResourceVisibility, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visibility, true
}

// SetVisibility sets field value
func (o *IntegrationsSchemasApiToolTool) SetVisibility(v ResourceVisibility) {
	o.Visibility = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IntegrationsSchemasApiToolTool) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IntegrationsSchemasApiToolTool) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IntegrationsSchemasApiToolTool) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetModifiedAt returns the ModifiedAt field value
func (o *IntegrationsSchemasApiToolTool) GetModifiedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
func (o *IntegrationsSchemasApiToolTool) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedAt, true
}

// SetModifiedAt sets field value
func (o *IntegrationsSchemasApiToolTool) SetModifiedAt(v time.Time) {
	o.ModifiedAt = v
}

// GetActive returns the Active field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrationsSchemasApiToolTool) GetActive() bool {
	if o == nil || IsNil(o.Active.Get()) {
		var ret bool
		return ret
	}
	return *o.Active.Get()
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrationsSchemasApiToolTool) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Active.Get(), o.Active.IsSet()
}

// HasActive returns a boolean if a field has been set.
func (o *IntegrationsSchemasApiToolTool) HasActive() bool {
	if o != nil && o.Active.IsSet() {
		return true
	}

	return false
}

// SetActive gets a reference to the given NullableBool and assigns it to the Active field.
func (o *IntegrationsSchemasApiToolTool) SetActive(v bool) {
	o.Active.Set(&v)
}
// SetActiveNil sets the value for Active to be an explicit nil
func (o *IntegrationsSchemasApiToolTool) SetActiveNil() {
	o.Active.Set(nil)
}

// UnsetActive ensures that no value is present for Active, not even an explicit nil
func (o *IntegrationsSchemasApiToolTool) UnsetActive() {
	o.Active.Unset()
}

func (o IntegrationsSchemasApiToolTool) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationsSchemasApiToolTool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if o.SystemPrompt.IsSet() {
		toSerialize["system_prompt"] = o.SystemPrompt.Get()
	}
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	if o.Jsonschema != nil {
		toSerialize["jsonschema"] = o.Jsonschema
	}
	toSerialize["execution_config"] = o.ExecutionConfig.Get()
	toSerialize["visibility"] = o.Visibility
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["modified_at"] = o.ModifiedAt
	if o.Active.IsSet() {
		toSerialize["active"] = o.Active.Get()
	}
	return toSerialize, nil
}

func (o *IntegrationsSchemasApiToolTool) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"execution_config",
		"visibility",
		"created_at",
		"modified_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrationsSchemasApiToolTool := _IntegrationsSchemasApiToolTool{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varIntegrationsSchemasApiToolTool)

	if err != nil {
		return err
	}

	*o = IntegrationsSchemasApiToolTool(varIntegrationsSchemasApiToolTool)

	return err
}

type NullableIntegrationsSchemasApiToolTool struct {
	value *IntegrationsSchemasApiToolTool
	isSet bool
}

func (v NullableIntegrationsSchemasApiToolTool) Get() *IntegrationsSchemasApiToolTool {
	return v.value
}

func (v *NullableIntegrationsSchemasApiToolTool) Set(val *IntegrationsSchemasApiToolTool) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationsSchemasApiToolTool) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationsSchemasApiToolTool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationsSchemasApiToolTool(val *IntegrationsSchemasApiToolTool) *NullableIntegrationsSchemasApiToolTool {
	return &NullableIntegrationsSchemasApiToolTool{value: val, isSet: true}
}

func (v NullableIntegrationsSchemasApiToolTool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationsSchemasApiToolTool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


