/*
Mistral AI API

Testing BetaObservabilityChatCompletionEventsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cterence/mistral-client-go/mistral"
)

func Test_mistral_BetaObservabilityChatCompletionEventsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BetaObservabilityChatCompletionEventsAPIService GetChatCompletionEventIdsV1ObservabilityChatCompletionEventsSearchIdsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaObservabilityChatCompletionEventsAPI.GetChatCompletionEventIdsV1ObservabilityChatCompletionEventsSearchIdsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityChatCompletionEventsAPIService GetChatCompletionEventV1ObservabilityChatCompletionEventsEventIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var eventId string

		resp, httpRes, err := apiClient.BetaObservabilityChatCompletionEventsAPI.GetChatCompletionEventV1ObservabilityChatCompletionEventsEventIdGet(context.Background(), eventId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityChatCompletionEventsAPIService GetChatCompletionEventsV1ObservabilityChatCompletionEventsSearchPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaObservabilityChatCompletionEventsAPI.GetChatCompletionEventsV1ObservabilityChatCompletionEventsSearchPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityChatCompletionEventsAPIService GetSimilarChatCompletionEventsV1ObservabilityChatCompletionEventsEventIdSimilarEventsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var eventId string

		resp, httpRes, err := apiClient.BetaObservabilityChatCompletionEventsAPI.GetSimilarChatCompletionEventsV1ObservabilityChatCompletionEventsEventIdSimilarEventsGet(context.Background(), eventId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityChatCompletionEventsAPIService JudgeChatCompletionEventV1ObservabilityChatCompletionEventsEventIdLiveJudgingPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var eventId string

		resp, httpRes, err := apiClient.BetaObservabilityChatCompletionEventsAPI.JudgeChatCompletionEventV1ObservabilityChatCompletionEventsEventIdLiveJudgingPost(context.Background(), eventId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
