/*
Mistral AI API

Testing BetaAgentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cterence/mistral-client-go/mistral"
)

func Test_mistral_BetaAgentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsCreateOrUpdateAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsCreateOrUpdateAlias(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsDelete(context.Background(), agentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsDeleteAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsDeleteAlias(context.Background(), agentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsGet(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsGetVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string
		var version string

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsGetVersion(context.Background(), agentId, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsListPages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsListPages(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsListVersionAliases", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsListVersionAliases(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsListVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsListVersions(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsUpdate(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaAgentsAPIService AgentsApiV1AgentsUpdateVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.BetaAgentsAPI.AgentsApiV1AgentsUpdateVersion(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
