/*
Mistral AI API

Testing BetaConnectorsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cterence/mistral-client-go/mistral"
)

func Test_mistral_BetaConnectorsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BetaConnectorsAPIService ConnectorCallToolV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var toolName string
		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorCallToolV1(context.Background(), toolName, connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorCreateOrUpdateOrganizationCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorCreateOrUpdateOrganizationCredentialsV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorCreateOrUpdateUserCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorCreateOrUpdateUserCredentialsV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorCreateOrUpdateWorkspaceCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorCreateOrUpdateWorkspaceCredentialsV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorCreateV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorCreateV1(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorDeleteOrganizationCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var credentialsName string
		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorDeleteOrganizationCredentialsV1(context.Background(), credentialsName, connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorDeleteUserCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var credentialsName string
		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorDeleteUserCredentialsV1(context.Background(), credentialsName, connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorDeleteV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorId string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorDeleteV1(context.Background(), connectorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorDeleteWorkspaceCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var credentialsName string
		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorDeleteWorkspaceCredentialsV1(context.Background(), credentialsName, connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorGetAuthUrlV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorGetAuthUrlV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorGetAuthenticationMethodsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorGetAuthenticationMethodsV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorGetV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorGetV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorListOrganizationCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorListOrganizationCredentialsV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorListToolsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorListToolsV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorListUserCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorListUserCredentialsV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorListV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorListV1(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorListWorkspaceCredentialsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorIdOrName string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorListWorkspaceCredentialsV1(context.Background(), connectorIdOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaConnectorsAPIService ConnectorUpdateV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var connectorId string

		resp, httpRes, err := apiClient.BetaConnectorsAPI.ConnectorUpdateV1(context.Background(), connectorId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
