/*
Mistral AI API

Testing BetaObservabilityJudgesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cterence/mistral-client-go/mistral"
)

func Test_mistral_BetaObservabilityJudgesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BetaObservabilityJudgesAPIService CreateJudgeV1ObservabilityJudgesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaObservabilityJudgesAPI.CreateJudgeV1ObservabilityJudgesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityJudgesAPIService DeleteJudgeV1ObservabilityJudgesJudgeIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var judgeId string

		httpRes, err := apiClient.BetaObservabilityJudgesAPI.DeleteJudgeV1ObservabilityJudgesJudgeIdDelete(context.Background(), judgeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityJudgesAPIService GetJudgeByIdV1ObservabilityJudgesJudgeIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var judgeId string

		resp, httpRes, err := apiClient.BetaObservabilityJudgesAPI.GetJudgeByIdV1ObservabilityJudgesJudgeIdGet(context.Background(), judgeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityJudgesAPIService GetJudgesV1ObservabilityJudgesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaObservabilityJudgesAPI.GetJudgesV1ObservabilityJudgesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityJudgesAPIService JudgeConversationV1ObservabilityJudgesJudgeIdLiveJudgingPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var judgeId string

		resp, httpRes, err := apiClient.BetaObservabilityJudgesAPI.JudgeConversationV1ObservabilityJudgesJudgeIdLiveJudgingPost(context.Background(), judgeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaObservabilityJudgesAPIService UpdateJudgeV1ObservabilityJudgesJudgeIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var judgeId string

		httpRes, err := apiClient.BetaObservabilityJudgesAPI.UpdateJudgeV1ObservabilityJudgesJudgeIdPut(context.Background(), judgeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
