/*
Mistral AI API

Testing BetaWorkflowsSchedulesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/cterence/mistral-client-go/mistral"
)

func Test_mistral_BetaWorkflowsSchedulesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BetaWorkflowsSchedulesAPIService GetSchedulesV1WorkflowsSchedulesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaWorkflowsSchedulesAPI.GetSchedulesV1WorkflowsSchedulesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsSchedulesAPIService ScheduleWorkflowV1WorkflowsSchedulesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BetaWorkflowsSchedulesAPI.ScheduleWorkflowV1WorkflowsSchedulesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaWorkflowsSchedulesAPIService UnscheduleWorkflowV1WorkflowsSchedulesScheduleIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scheduleId string

		httpRes, err := apiClient.BetaWorkflowsSchedulesAPI.UnscheduleWorkflowV1WorkflowsSchedulesScheduleIdDelete(context.Background(), scheduleId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
